const categories = ['football', 'basketball'];

const betTypesFootball = [
    'Tiempo reglamentario',
    'Total de goles',
    'Doble Oportunidad',
    'Se clasifica para la siguiente ronda',
    'Ambos Equipos Marcarán',
    'Gol en ambas mitades',
    'Total de goles - 2.ª parte',
    'Ambos Equipos Marcarán - 2.ª parte',
    'Doble Oportunidad - 2.ª parte',
    '2.ª parte',
    'Total de goles - 1.ª parte',
    'Ambos Equipos Marcarán - 1.ª parte',
    'Doble Oportunidad - 1.ª parte',
    'Total de Tiros de Esquina',
    'Más Tiros de Esquina',
    'Total de tarjetas',
    'Tarjeta Roja mostrada',
    'Más Tarjetas',
];

const betTypesBaketball = [
    'Prórroga incluida',
    'Total de puntos - Prórroga incluida'
];

const idsFootball = {};
for (let i = 0; i < betTypesFootball.length; i++) {
    idsFootball[betTypesFootball[i]] = i + 1;
}

const idsBasketball = {};
for (let i = 0; i < betTypesBaketball.length; i++) {
    idsBasketball[betTypesBaketball[i]] = i + 1;
}

const betDescriptionsFootball = {
    'Total de goles': {
        betplay: 'Total de goles',
        wplay: 'Total Goles Más/Menos de',
        betsson: 'número de goles',
        '1xbet': 'Total',
        codere: 'Más/Menos Total Goles',
        yaJuegos: 'Totales',
        luckia: 'Menos/Más',
        sportium: 'Total de goles Más/Menos',
        zamba: 'Total',
        wonderbet: 'Total Goles - Más / Menos',
        megapuesta: 'Total Goles',
        fullreto: 'Total de goles',
        betboro: 'Total de goles',
    },
    'Tiempo reglamentario': {
        betplay: 'Tiempo reglamentario',
        wplay: 'Resultado Tiempo Completo',
        betsson: 'ganador del partido',
        '1xbet': '1x2',
        codere: '1X2',
        yaJuegos: '1X2',
        luckia: '1x2',
        sportium: '1X2',
        zamba: '1x2',
        wonderbet: 'Ganador',
        megapuesta: 'Final',
        fullreto: '1x2',
        betboro: 'Resultado del Partido',
    },
    'Doble Oportunidad': {
        betplay: 'Doble Oportunidad',
        wplay: 'Doble Oportunidad',
        betsson: 'doble oportunidad',
        '1xbet': 'Doble oportunidad',
        codere: 'Doble Oportunidad',
        yaJuegos: 'Doble oportunidad',
        luckia: 'Doble oportunidad',
        sportium: 'Doble Oportunidad',
        zamba: 'Doble oportunidad',
        wonderbet: 'Doble Oportunidad',
        megapuesta: 'Doble Oportunidad',
        fullreto: 'Doble oportunidad',
        betboro: 'Doble Oportunidad',
    },
    'Se clasifica para la siguiente ronda': {
        betplay: 'Se clasifica para la siguiente ronda',
        wplay: 'Se clasificará',
        betsson: 'avanza a la siguiente fase',
        '1xbet': 'Se clasificará',
        codere: 'Clasificarse',
        yaJuegos: '',
        luckia: 'Ganador sin empate',
        sportium: 'Clasificarse',
        zamba: 'Apuesta sin empate',
        wonderbet: 'Empate Apuesta No Válida',
        megapuesta: 'Apuesta sin Empate',
        fullreto: 'Se clasifica',
        betboro: 'Clasificará',
    },
    'Ambos Equipos Marcarán': {
        betplay: 'Ambos Equipos Marcarán',
        wplay: 'Ambos Equipos Anotan',
        betsson: 'ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán',
        codere: 'Marcan Ambos Equipos',
        yaJuegos: 'Ambos equipos marcarán',
        luckia: 'Ambos equipos marcarán',
        sportium: 'Marcan ambos equipos',
        zamba: 'Ambos equipos marcan',
        wonderbet: 'ambos equipos anotaran',
        megapuesta: 'Ambos Equipos Marcarán',
        fullreto: 'Ambos equipos marcan',
        betboro: 'Ambos equipos marcan',
    },
    'Gol en ambas mitades': {
        betplay: 'Gol en ambas mitades',
        wplay: 'Se anotarán goles en ambas mitades',
        betsson: 'gol en ambos tiempos',
        '1xbet': 'Goles en ambas mitades',
        codere: 'Goles en ambas mitades',
        yaJuegos: 'Goles en ambas mitades',
        luckia: 'Goles en ambas mitades',
        // sportium: 'Ambos marcan ambas partes',
        zamba: 'Goles en ambas mitades',
        wonderbet: 'Goles en ambas mitades',
        megapuesta: 'Goles en ambas mitades',
        fullreto: 'Goles en ambas mitades',
        betboro: 'Goles en ambas mitades',
    },
    'Total de goles - 2.ª parte': {
        betplay: 'Total de goles - 2.ª parte',
        wplay: '2ª Mitad - más/Menos de',
        '1xbet': 'Total. 2 Mitad',
        codere: '2ª Parte - Más/Menos Total Goles',
        yaJuegos: '',
        luckia: '2ª mitad - Menos/Más',
        sportium: '2ª Mitad - Total de Goles',
        zamba: '2º Mitad - total',
        wonderbet: '2° Tiempo - Más de/Menos de',
        megapuesta: '2ª M Total Goles',
        fullreto: '2ª Mitad - total',
        betboro: '2da mitad Total de  goles',
    },
    'Ambos Equipos Marcarán - 2.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 2.ª parte',
        wplay: 'Ambos Equipos anotarán en la 2da Mitad',
        '1xbet': 'Ambos equipos anotarán. 2 Mitad',
        codere: '2ª Parte - Marcan Ambos Equipos',
        yaJuegos: '',
        luckia: '2ª mitad - Ambos equipos marcarán',
        sportium: '2ª Mitad - Ambos equipos marcarán',
        zamba: '2º Mitad - ambos equipos marcan',
        wonderbet: '2° Tiempo - Ambos equipos marcan',
        megapuesta: '2ª Mitad Ambos Equipos Marcarán',
        fullreto: '2ª Mitad - ambos equipos marcan',
        betboro: '2da mitad Ambos equipos anotarán',
    },
    'Doble Oportunidad - 2.ª parte': {
        betplay: 'Doble Oportunidad - 2.ª parte',
        '1xbet': 'Doble oportunidad. 2 Mitad',
        codere: '2ª Parte - Doble Oportunidad',
        yaJuegos: '',
        luckia: '2ª mitad - Doble oportunidad',
        zamba: '2º Mitad - doble oportunidad',
        wonderbet: '2° Tiempo - Doble Oportunidad',
        // megapuesta: '2ª M Total Goles 0.5',
        fullreto: '2ª Mitad - doble oportunidad',
        betboro: '2da Mitad Doble Oportunidad',
    },
    '2.ª parte': {
        betplay: '2.ª parte',
        wplay: 'Resultado 2da Mitad',
        betsson: 'resultado del 2do tiempo',
        '1xbet': '1x2. 2 Mitad',
        codere: '2ª Parte - 1X2',
        yaJuegos: '',
        luckia: '2ª mitad - 1X2',
        sportium: 'Resultado 2ª Mitad',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - Ganador (1-X-2)',
        megapuesta: '2ª Mitad',
        fullreto: '2ª Mitad - 1x2',
        betboro: 'Resultado de la Segunda Mitad',
    },
    'Total de goles - 1.ª parte': {
        betplay: 'Total de goles - 1.ª parte',
        wplay: '1ra Mitad Total de Goles más/Menos de',
        '1xbet': 'Total. 1 Mitad',
        codere: '1ª Parte - Más/Menos Total Goles',
        yaJuegos: '',
        luckia: '1ª mitad - Menos/Más',
        sportium: '1ª Mitad - Total de Goles',
        zamba: '1º Mitad - total',
        wonderbet: '1° Tiempo - Más de/Menos de',
        megapuesta: '1ª M Total Goles',
        fullreto: '1ª Mitad - total',
        betboro: 'Total de Goles de la 1ra mitad',
    },
    'Ambos Equipos Marcarán - 1.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 1.ª parte',
        wplay: 'Ambos Equipos anotarán en la 1er Mitad',
        betsson: '1er tiempo - ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán. 1 Mitad',
        codere: '1ª Parte - Marcan Ambos Equipos',
        yaJuegos: '',
        luckia: '1ª mitad - Ambos equipos marcarán',
        sportium: '1ª Mitad - Ambos equipos marcarán',
        zamba: '1º Mitad - ambos equipos marcan',
        wonderbet: '1° Tiempo - Ambos equipos marcan',
        megapuesta: '1ª Mitad Ambos Equipos Marcarán',
        fullreto: '1ª Mitad - ambos equipos marcan',
        betboro: '1ra mitad: Ambos Equipos Anotarán',
    },
    'Doble Oportunidad - 1.ª parte': {
        betplay: 'Doble Oportunidad - 1.ª parte',
        wplay: 'Doble Oportunidad 1ª Mitad',
        betsson: '1er tiempo - doble oportunidad',
        '1xbet': 'Doble oportunidad. 1 Mitad',
        codere: '1ª Parte - Doble Oportunidad',
        yaJuegos: '',
        luckia: '1ª mitad - Doble oportunidad',
        sportium: '1ª Mitad - Doble Oportunidad',
        zamba: '1º Mitad - doble oportunidad',
        wonderbet: '1° Tiempo - Doble Oportunidad',
        fullreto: '1ª Mitad - doble oportunidad',
        betboro: '1ra mitad: Doble Oportunidad',
    },
    'Total de Tiros de Esquina': {
        betplay: 'Total de Tiros de Esquina',
        wplay: 'Tiros de esquina más/Menos de (9.5)',
        betsson: 'total tiros de esquina',
        '1xbet': 'Total. Saques de esquina',
        codere: 'Total de Córner Más/Menos',
        yaJuegos: '',
        luckia: 'Menos/Más corners',
        sportium: 'Total de córners',
        zamba: 'Total córneres',
        wonderbet: 'Total tiros de esquina',
        megapuesta: 'Total Esquinas',
        fullreto: 'Total Tiros De Esquina',
        betboro: 'Córneres: Total',
    },
    'Más Tiros de Esquina': {
        betplay: 'Más Tiros de Esquina',
        wplay: 'Equipo con más Tiros de Esquina',
        betsson: 'mayor número de tiros de esquina',
        '1xbet': '1x2. Saques de esquina',
        codere: 'Equipo con Más Córner',
        yaJuegos: '',
        luckia: 'Corners - 1X2',
        sportium: 'Mayor número de córners',
        zamba: 'Córner 1x2',
        wonderbet: 'Equipo que sacará más corners (1-X-2)',
        megapuesta: 'Esquninas 1X2',
        fullreto: 'Córner 1x2',
        betboro: 'Córneres: Resultado',
    },
    'Total de tarjetas': {
        betplay: 'Total de tarjetas',
        wplay: 'Total de Tarjetas (3.5)',
        betsson: 'total de tarjetas',
        '1xbet': 'Total. Tarjetas amarillas',
        codere: 'Total de Tarjetas Más/Menos',
        yaJuegos: '',
        luckia: 'Menos/Más tarjetas (jugadores en juego)',
        sportium: 'Total de tarjetas',
        zamba: 'Total tarjetas',
        wonderbet: 'Total de tarjetas en el partido',
        megapuesta: 'Total Tarjetas',
        fullreto: 'Total tarjetas',
        betboro: 'Tarjetas Amarillas: Total',
    },
    'Tarjeta Roja mostrada': {
        betplay: 'Tarjeta Roja mostrada',
        betsson: 'tarjetas rojas',
        codere: '¿Habrá Tarjeta Roja?',
        yaJuegos: '',
        luckia: '¿Habrá alguna expulsión en el partido? (jugadores en juego)',
        zamba: 'Expulsión',
        megapuesta: 'Expulsión',
        fullreto: 'Expulsión',
        betboro: 'Una tarjeta roja en el partido',
    },
    'Más Tarjetas': {
        betplay: 'Más Tarjetas',
        betsson: 'más puntos de amonestación',
        '1xbet': '1x2. Tarjetas amarillas',
        codere: 'Equipo con Más Tarjetas',
        yaJuegos: '',
        luckia: 'Tarjetas - 1X2 (jugadores en juego)',
        zamba: 'Tarjeta 1x2',
        wonderbet: 'Equipo que verá más tarjetas en el partido (1-X-2)',
        megapuesta: '1X2 Tarjetas',
        fullreto: 'Tarjetas 1x2',
        betboro: 'Tarjetas Amarillas: Resultado',
    },
    '': {
        betplay: '',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },

};

const betDescriptionsBasketball = {
    'Prórroga incluida': {
        betplay: 'Prórroga incluida',
        wplay: 'Lineas del Juego',
        betsson: 'ganador - partido',
        '1xbet': 'Victoria del equipo',
        codere: 'Ganador del Partido',
        yaJuegos: 'Totales',
        luckia: 'Ganador del partido (incl. prórroga)',
        sportium: 'Handicap de Juegos',
        zamba: 'Ganador (incl. prórroga)',
        wonderbet: 'Ganador del Partido',
        megapuesta: 'Ganador (Inc. Pró.)',
        fullreto: 'Ganador (incl. prórroga)',
        betboro: 'Ganador (incl. prórroga)',
    },
    'Total de puntos - Prórroga incluida': {
        betplay: 'Total de puntos - Prórroga incluida',
        wplay: 'Total Puntos (Inc. Prórroga)',
        betsson: 'puntos totales',
        '1xbet': 'Total',
        codere: 'Más/Menos Puntos Totales',
        yaJuegos: 'Totales',
        luckia: 'Menos/más (incl. prórroga)',
        sportium: 'Total de puntos',
        zamba: 'Total (incl. prórroga)',
        wonderbet: 'Más / Menos',
        megapuesta: 'Total (incl. prórroga)',
        fullreto: 'Totales (incl. prórroga)',
        betboro: 'Totales (incl. prórroga)',
    },
}

module.exports = {
    categories,
    betTypesFootball,
    idsFootball,
    betTypesBaketball,
    idsBasketball,
    betDescriptionsFootball,
    betDescriptionsBasketball
}