
const categories = ['football', 'basketball', /*  'basketball',*/];

const betTypesFootball = [
    'Tiempo reglamentario',
    'Total de goles',
    'Doble Oportunidad',
    'Se clasifica para la siguiente ronda',
    'Ambos Equipos Marcarán',
    'Hándicap 3-Way',
    'Gol en ambas mitades',
    'Total de goles - 2.ª parte',
    'Ambos Equipos Marcarán - 2.ª parte',
    'Doble Oportunidad - 2.ª parte',
    '2.ª parte',
    'Total de goles - 1.ª parte',
    'Ambos Equipos Marcarán - 1.ª parte',
    'Doble Oportunidad - 1.ª parte',
    'Total de Tiros de Esquina - 1.ª parte',
    'Total de Tiros de Esquina',
    'Más Tiros de Esquina',
    'Total de tarjetas',
    'Tarjeta Roja mostrada',
    'Más Tarjetas',
];

const betTypesBaketball = [
    'Prórroga incluida',
    'Total de puntos - Prórroga incluida',
    '1.ª parte',
    'Apuesta sin empate - 1.ª parte',
    'Total de puntos - 1.ª parte',
    '2.ª parte',
    'Apuesta sin empate - 2.ª parte',
    'Total de puntos - 2.ª parte',
    'Cuarto 1',
    'Apuesta sin empate - Cuarto 1',
    'Total de puntos - Cuarto 1',
    'Cuarto 2',
    'Apuesta sin empate - Cuarto 2',
    'Total de puntos - Cuarto 2',
    'Cuarto 3',
    'Apuesta sin empate - Cuarto 3',
    'Total de puntos - Cuarto 3',
    'Cuarto 4',
    'Apuesta sin empate - Cuarto 4',
    'Total de puntos - Cuarto 4',
];

const betTypesTennis = [
    'Cuotas del partido',
    'Total de juegos',
    'Total de sets',
    'Set 1',
    'Set 2',
    'Total de juegos - Set 1',
    'Total de juegos - Set 2',
];

const idsFootball = {};
for (let i = 0; i < betTypesFootball.length; i++) {
    idsFootball[betTypesFootball[i]] = i + 1;
}

const idsBasketball = {};
for (let i = 0; i < betTypesBaketball.length; i++) {
    idsBasketball[betTypesBaketball[i]] = i + 1;
}

const idsTennis = {};
for (let i = 0; i < betTypesTennis.length; i++) {
    idsTennis[betTypesTennis[i]] = i + 1;
}

const betDescriptionsFootball = {
    'Total de goles': {
        betplay: 'Total de goles',
        wplay: 'Total Goles Más/Menos de',
        betsson: 'número de goles',
        '1xbet': 'Total',
        codere: 'Más/Menos Total Goles',
        yaJuegos: 'Totales',
        luckia: 'Menos/Más',
        sportium: 'Total de goles Más/Menos',
        zamba: 'Total',
        wonderbet: 'Total Goles - Más / Menos',
        megapuesta: 'Total Goles',
        fullreto: 'Total de goles',
        betboro: 'Total de goles',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos - Tiempo Regular',
        cashwin: 'Total',
        bwin: 'Total de goles',
        lsbet: 'Gesamtzahl Tore mehr als / weniger als',
    },
    'Tiempo reglamentario': {
        betplay: 'Tiempo reglamentario',
        wplay: 'Resultado Tiempo Completo',
        betsson: 'ganador del partido',
        '1xbet': '1x2',
        codere: '1X2',
        yaJuegos: '1X2',
        luckia: '1x2',
        sportium: '1X2',
        zamba: '1x2',
        wonderbet: 'Ganador',
        megapuesta: 'Final',
        fullreto: '1x2',
        betboro: 'Resultado del Partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Resultado - Tiempo Regular',
        cashwin: '1x2',
        bwin: 'Resultado del partido',
        lsbet: 'Match Ergebnis'
    },
    'Doble Oportunidad': {
        betplay: 'Doble Oportunidad',
        wplay: 'Doble Oportunidad',
        betsson: 'doble oportunidad',
        '1xbet': 'Doble oportunidad',
        codere: 'Doble Oportunidad',
        yaJuegos: 'Doble oportunidad',
        luckia: 'Doble oportunidad',
        sportium: 'Doble Oportunidad',
        zamba: 'Doble oportunidad',
        wonderbet: 'Doble Oportunidad',
        megapuesta: 'Doble Oportunidad',
        fullreto: 'Doble oportunidad',
        betboro: 'Doble Oportunidad',
        pinnacle: 'Double Chance',
        dafabet: 'Doble oportunidad - Tiempo Regular',
        cashwin: 'Double chance',
        bwin: 'Doble oportunidad',
        lsbet: 'Doppelte Chance'
    },
    'Se clasifica para la siguiente ronda': {
        betplay: 'Se clasifica para la siguiente ronda',
        wplay: 'Se clasificará',
        betsson: 'avanza a la siguiente fase',
        '1xbet': 'Se clasificará',
        codere: 'Clasificarse',
        yaJuegos: '',
        luckia: 'Se clasificará',
        sportium: 'Clasificarse',
        // zamba: 'Apuesta sin empate',
        // wonderbet: 'Empate Apuesta No Válida',
        // megapuesta: 'Apuesta sin Empate',
        fullreto: 'Se clasifica',
        betboro: 'Clasificará',
        pinnacle: 'Línea de dinero – Para calificar',
        cashwin: 'Draw no bet',
        bwin: 'Se clasifica',
        lsbet: 'Zu Qualifizieren'
    },
    'Ambos Equipos Marcarán': {
        betplay: 'Ambos Equipos Marcarán',
        wplay: 'Ambos Equipos Anotan',
        betsson: 'ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán',
        codere: 'Marcan Ambos Equipos',
        yaJuegos: 'Ambos equipos marcarán',
        luckia: 'Ambos equipos marcarán',
        sportium: 'Marcan ambos equipos',
        zamba: 'Ambos equipos marcan',
        wonderbet: 'ambos equipos anotaran',
        megapuesta: 'Ambos Equipos Marcarán',
        fullreto: 'Ambos equipos marcan',
        betboro: 'Ambos equipos marcan',
        pinnacle: '¿Anotarán los dos equipos?',
        dafabet: 'Ambos equipos marcan - Tiempo Regular',
        bwin: 'Ambos equipos marcan',
        lsbet: 'Beide Teams treffen'
    },
    'Gol en ambas mitades': {
        betplay: 'Gol en ambas mitades',
        wplay: 'Se anotarán goles en ambas mitades',
        betsson: 'gol en ambos tiempos',
        '1xbet': 'Goles en ambas mitades',
        codere: 'Goles en ambas mitades',
        yaJuegos: 'Goles en ambas mitades',
        luckia: 'Goles en ambas mitades',
        // sportium: 'Ambos marcan ambas partes',
        zamba: 'Goles en ambas mitades',
        wonderbet: 'Goles en ambas mitades',
        megapuesta: 'Goles en ambas mitades',
        fullreto: 'Goles en ambas mitades',
        betboro: 'Goles en ambas mitades',
        cashwin: '1st/2nd half both teams to score',
        bwin: 'Goles que se marcan en ambas partes'
    },
    'Total de goles - 2.ª parte': {
        betplay: 'Total de goles - 2.ª parte',
        wplay: '2ª Mitad - más/Menos de',
        '1xbet': 'Total. 2 Mitad',
        codere: '2ª Parte - Más/Menos Total Goles',
        yaJuegos: '',
        luckia: '2ª mitad - Menos/Más',
        sportium: '2ª Mitad - Total de Goles',
        zamba: '2º Mitad - total',
        wonderbet: '2° Tiempo - Más de/Menos de',
        megapuesta: '2ª M Total Goles',
        fullreto: '2ª Mitad - total',
        betboro: '2da mitad Total de  goles',
        dafabet: 'Más/Menos - Segundo tiempo',
        cashwin: '2nd half - total',
        bwin: 'Total de goles-2º tiempo',
    },
    'Ambos Equipos Marcarán - 2.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 2.ª parte',
        wplay: 'Ambos Equipos anotarán en la 2da Mitad',
        '1xbet': 'Ambos equipos anotarán. 2 Mitad',
        codere: '2ª Parte - Marcan Ambos Equipos',
        yaJuegos: '',
        luckia: '2ª mitad - Ambos equipos marcarán',
        sportium: '2ª Mitad - Ambos equipos marcarán',
        zamba: '2º Mitad - ambos equipos marcan',
        wonderbet: '2° Tiempo - Ambos equipos marcan',
        megapuesta: '2ª Mitad Ambos Equipos Marcarán',
        fullreto: '2ª Mitad - ambos equipos marcan',
        betboro: '2da mitad Ambos equipos anotarán',
        cashwin: '2nd half - both teams to score',
        bwin: 'Ambos equipos marcan-2º tiempo'
    },
    'Doble Oportunidad - 2.ª parte': {
        betplay: 'Doble Oportunidad - 2.ª parte',
        '1xbet': 'Doble oportunidad. 2 Mitad',
        codere: '2ª Parte - Doble Oportunidad',
        yaJuegos: '',
        luckia: '2ª mitad - Doble oportunidad',
        zamba: '2º Mitad - doble oportunidad',
        wonderbet: '2° Tiempo - Doble Oportunidad',
        // megapuesta: '2ª M Total Goles 0.5',
        fullreto: '2ª Mitad - doble oportunidad',
        betboro: '2da Mitad Doble Oportunidad',
        cashwin: '2nd half - total',
        bwin: 'Doble oportunidad-2º tiempo'
    },
    '2.ª parte': {
        betplay: '2.ª parte',
        wplay: 'Resultado 2da Mitad',
        betsson: 'resultado del 2do tiempo',
        '1xbet': '1x2. 2 Mitad',
        codere: '2ª Parte - 1X2',
        yaJuegos: '',
        luckia: '2ª mitad - 1X2',
        sportium: 'Resultado 2ª Mitad',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - Ganador (1-X-2)',
        megapuesta: '2ª Mitad',
        fullreto: '2ª Mitad - 1x2',
        betboro: 'Resultado de la Segunda Mitad',
        dafabet: 'Resultado - Segundo tiempo',
        cashwin: '2nd half - 1x2',
        bwin: 'Resultado del partido-2º tiempo',
        lsbet: 'Second Half Result',
    },
    'Total de goles - 1.ª parte': {
        betplay: 'Total de goles - 1.ª parte',
        wplay: '1ra Mitad Total de Goles más/Menos de',
        '1xbet': 'Total. 1 Mitad',
        codere: '1ª Parte - Más/Menos Total Goles',
        yaJuegos: '',
        luckia: '1ª mitad - Menos/Más',
        sportium: '1ª Mitad - Total de Goles',
        zamba: '1º Mitad - total',
        wonderbet: '1° Tiempo - Más de/Menos de',
        megapuesta: '1ª M Total Goles',
        fullreto: '1ª Mitad - total',
        betboro: 'Total de Goles de la 1ra mitad',
        pinnacle: 'Total – 1.ª parte',
        dafabet: 'Más/Menos - Primer tiempo',
        cashwin: '1st half - total',
        bwin: 'Total de goles-1º tiempo',
        lsbet: 'Half-time Totals Over/Under',
    },
    'Ambos Equipos Marcarán - 1.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 1.ª parte',
        wplay: 'Ambos Equipos anotarán en la 1er Mitad',
        betsson: '1er tiempo - ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán. 1 Mitad',
        codere: '1ª Parte - Marcan Ambos Equipos',
        yaJuegos: '',
        luckia: '1ª mitad - Ambos equipos marcarán',
        sportium: '1ª Mitad - Ambos equipos marcarán',
        zamba: '1º Mitad - ambos equipos marcan',
        wonderbet: '1° Tiempo - Ambos equipos marcan',
        megapuesta: '1ª Mitad Ambos Equipos Marcarán',
        fullreto: '1ª Mitad - ambos equipos marcan',
        betboro: '1ra mitad: Ambos Equipos Anotarán',
        pinnacle: 'Both Teams To Score? 1st Half',
        dafabet: 'Ambos equipos marcan - Primer tiempo',
        cashwin: '1st half - 1x2 & both teams to score',
        bwin: 'Ambos equipos marcan-1º tiempo',
        lsbet: 'Half-time Both Teams To Score Yes/No'
    },
    'Doble Oportunidad - 1.ª parte': {
        betplay: 'Doble Oportunidad - 1.ª parte',
        wplay: 'Doble Oportunidad 1ª Mitad',
        betsson: '1er tiempo - doble oportunidad',
        '1xbet': 'Doble oportunidad. 1 Mitad',
        codere: '1ª Parte - Doble Oportunidad',
        yaJuegos: '',
        luckia: '1ª mitad - Doble oportunidad',
        sportium: '1ª Mitad - Doble Oportunidad',
        zamba: '1º Mitad - doble oportunidad',
        wonderbet: '1° Tiempo - Doble Oportunidad',
        fullreto: '1ª Mitad - doble oportunidad',
        betboro: '1ra mitad: Doble Oportunidad',
        pinnacle: 'Double Chance 1st Half',
        dafabet: 'Doble oportunidad - Primer tiempo',
        cashwin: '1st half - double chance',
        bwin: 'Doble oportunidad-1º tiempo',
        lsbet: 'Erste Hälfte   Doppelte Chance'
    },
    'Total de Tiros de Esquina': {
        betplay: 'Total de Tiros de Esquina',
        wplay: 'Tiros de esquina más/Menos de (9.5)',
        betsson: 'total tiros de esquina',
        '1xbet': 'Total. Saques de esquina',
        codere: 'Total de Córner Más/Menos',
        yaJuegos: '',
        luckia: 'Menos/Más corners',
        sportium: 'Total de córners',
        zamba: 'Total córneres',
        wonderbet: 'Total tiros de esquina',
        megapuesta: 'Total Esquinas',
        fullreto: 'Total Tiros De Esquina',
        betboro: 'Córneres: Total',
        pinnacle: 'Total (Córneres) – Partido',
        dafabet: 'Corners Más/Menos - Tiempo Regular',
        cashwin: 'Total corners',
        bwin: 'Número de córners',
        lsbet: 'Total Corners Over/Under'
    },
    'Más Tiros de Esquina': {
        betplay: 'Más Tiros de Esquina',
        wplay: 'Equipo con más Tiros de Esquina',
        betsson: 'mayor número de tiros de esquina',
        '1xbet': '1x2. Saques de esquina',
        codere: 'Equipo con Más Córner',
        yaJuegos: '',
        luckia: 'Corners - 1X2',
        sportium: 'Mayor número de córners',
        zamba: 'Córner 1x2',
        wonderbet: 'Equipo que sacará más corners (1-X-2)',
        megapuesta: 'Esquninas 1X2',
        fullreto: 'Córner 1x2',
        betboro: 'Córneres: Resultado',
        dafabet: 'Más corners - Tiempo Regular',
        cashwin: 'Corner 1x2',
        bwin: 'Córners',
        lsbet: 'Team With Most Corners (With Draw)'
    },
    'Total de tarjetas': {
        betplay: 'Total de tarjetas',
        wplay: 'Total de Tarjetas (3.5)',
        betsson: 'total de tarjetas',
        '1xbet': 'Total. Tarjetas amarillas',
        codere: 'Total de Tarjetas Más/Menos',
        yaJuegos: '',
        luckia: 'Menos/Más tarjetas (jugadores en juego)',
        sportium: 'Total de tarjetas',
        zamba: 'Total tarjetas',
        wonderbet: 'Total de tarjetas en el partido',
        megapuesta: 'Total Tarjetas',
        fullreto: 'Total tarjetas',
        betboro: 'Tarjetas Amarillas: Total',
        pinnacle: 'Total (Tarjetas) – Partido',
        dafabet: 'Bookings Más/Menos - Tiempo Regular',
        cashwin: 'Total bookings',
        bwin: 'Número total de tarjetas amarillas',
        lsbet: 'Gesamtzahl der Karten Über / Unter'
    },
    'Tarjeta Roja mostrada': {
        betplay: 'Tarjeta Roja mostrada',
        betsson: 'tarjetas rojas',
        codere: '¿Habrá Tarjeta Roja?',
        yaJuegos: '',
        luckia: '¿Habrá alguna expulsión en el partido? (jugadores en juego)',
        zamba: 'Expulsión',
        megapuesta: 'Expulsión',
        fullreto: 'Expulsión',
        betboro: 'Una tarjeta roja en el partido',
        dafabet: 'Expulsión (tarjeta roja) - Tiempo Regular',
        bwin: 'Tarjeta roja - Sí/No'
    },
    'Más Tarjetas': {
        betplay: 'Más Tarjetas',
        betsson: 'más puntos de amonestación',
        '1xbet': '1x2. Tarjetas amarillas',
        codere: 'Equipo con Más Tarjetas',
        yaJuegos: '',
        luckia: 'Tarjetas - 1X2 (jugadores en juego)',
        zamba: 'Tarjeta 1x2',
        wonderbet: 'Equipo que verá más tarjetas en el partido (1-X-2)',
        megapuesta: '1X2 Tarjetas',
        fullreto: 'Tarjetas 1x2',
        betboro: 'Tarjetas Amarillas: Resultado',
        dafabet: 'Más Tarjetas - Tiempo Regular',
        cashwin: 'Booking 1x2',
        bwin: 'Más tarjetas amarillas'
    },
    'Total de Tiros de Esquina - 1.ª parte': {
        betplay: 'Total de Tiros de Esquina - 1.ª parte',
        // wplay: '',
        // betsson: '',
        // '1xbet': '',
        // codere: '',
        // yaJuegos: '',
        // luckia: '',
        // sportium: '',
        // zamba: '',
        // wonderbet: '',
        // megapuesta: '',
        // fullreto: '',
        // betboro: '',
        dafabet: 'Corners Más/Menos - Primer tiempo',
        bwin: 'Número de córners-1º tiempo'
    },
    'Hándicap asiático - 1.ª parte': {
        betplay: 'Hándicap asiático - 1.ª parte',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Total asiático - 1.ª parte': {
        betplay: 'Total asiático - 1.ª parte',
        wplay: 'Handicap Asiático Total Goles 1ra Mitad',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Hándicap 3-Way': {
        betplay: 'Hándicap 3-Way',
        wplay: 'Handicap Resultado Partido',
        betsson: 'hándicap (3 opciones)',
        '1xbet': 'Hándicap',
        codere: '1X2 Handicap',
        yaJuegos: '',
        luckia: '1X2 - Hándicap',
        sportium: '1X2 Handicap',
        // zamba: '',
        // wonderbet: 'Handicap Europeo',
        // megapuesta: '',
        fullreto: 'Hándicap 1x2',
        betboro: ' Hándicap 3 opciones',
    },

};

const betDescriptionsBasketball = {
    'Prórroga incluida': {
        betplay: 'Prórroga incluida',
        wplay: 'Lineas del Juego',
        betsson: 'ganador - partido',
        '1xbet': 'Victoria del equipo',
        codere: 'Ganador del Partido',
        yaJuegos: 'Totales',
        luckia: 'Ganador del partido (incl. prórroga)',
        sportium: 'Handicap de Juegos',
        zamba: 'Ganador (incl. prórroga)',
        wonderbet: 'Ganador del Partido',
        megapuesta: 'Ganador (Inc. Pró.)',
        fullreto: 'Ganador (incl. prórroga)',
        betboro: 'Ganador del Partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Ganador - Partido',
        cashwin: 'Winner (incl. OT)',
    },
    'Total de puntos - Prórroga incluida': {
        betplay: 'Total de puntos - Prórroga incluida',
        wplay: 'Total Puntos (Inc. Prórroga)',
        betsson: 'puntos totales',
        '1xbet': 'Total',
        codere: 'Más/Menos Puntos Totales',
        yaJuegos: 'Totales',
        luckia: 'Menos/más (incl. prórroga)',
        sportium: 'Total de puntos',
        zamba: 'Total (incl. prórroga)',
        wonderbet: 'Más / Menos',
        megapuesta: 'Total (incl. prórroga)',
        fullreto: 'Totales (incl. prórroga)',
        betboro: 'Total de puntos',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos - Partido',
        cashwin: 'Total (incl. OT)',
    },
    'Cuarto 1': {
        betplay: 'Cuarto 1',
        wplay: '1er Cuarto Línea de Dinero 3 Opciones',
        betsson: 'resultado - 1er cuarto',
        '1xbet': '1X2. 1 Cuarto',
        // codere: '',
        // yaJuegos: '',
        luckia: 'Cuarto 1 - 1X2',
        sportium: '1º Cuarto -  Resultado',
        zamba: '1.º cuarto - 1x2',
        wonderbet: '1° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 1',
        fullreto: 'Primer cuarto - 1x2',
        betboro: '1ra Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 1º Cuarto',
        cashwin: 'First quarter - 1x2'
    },
    'Apuesta sin empate - Cuarto 1': {
        betplay: 'Apuesta sin empate - Cuarto 1',
        wplay: '1er Cuarto',
        betsson: 'ganador - 1er cuarto',
        // '1xbet': '',
        codere: 'Ganador 1º Cuarto (Sin Empate)',
        // yaJuegos: '',
        luckia: 'Cuarto 1 - Ganador sin empate',
        sportium: '1º Cuarto - Ganador (sin empate)',
        // zamba: '',
        wonderbet: '1° Cuarto - Empate Apuesta No Válida',
        // megapuesta: '',
        fullreto: 'Primer cuarto - apuesta sin empate',
        betboro: '1ra Cuarto Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 1.er cuarto',
        dafabet: 'Ganador - 1º Cuarto',
        cashwin: 'First quarter - draw no bet'
    },
    'Total de puntos - Cuarto 1': {
        betplay: 'Total de puntos - Cuarto 1',
        // wplay: '',
        betsson: 'total puntos - 1er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 1º Cuarto',
        yaJuegos: '',
        luckia: 'Cuarto 1 - Total',
        sportium: 'Más/Menos Total de Puntos 1º Cuarto',
        zamba: '1.º cuarto - total',
        wonderbet: '1° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 1',
        fullreto: 'Cuarto primer - total',
        betboro: '1ra Cuarto Total de puntos',
        pinnacle: 'Total – 1.er cuarto',
        dafabet: 'Más/Menos - 1º Cuarto',
        cashwin: 'First quarter - total',
        bwin: 'Total 1er cuarto',
    },
    'Cuarto 2': {
        betplay: 'Cuarto 2',
        wplay: '2do Cuarto Money Line 3 Opciones',
        betsson: 'resultado - 2do cuarto',
        '1xbet': '1X2. 2 Cuarto',
        // codere: '',
        yaJuegos: '',
        luckia: 'Cuarto 2 - 1X2',
        sportium: '2º Cuarto - Resultado',
        zamba: '2.º cuarto - 1x2',
        wonderbet: '2° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 2',
        fullreto: 'Segundo cuarto - 1x2',
        betboro: '2do Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 2º Cuarto',
        cashwin: 'Second quarter - 1x2'
    },
    'Apuesta sin empate - Cuarto 2': {
        betplay: 'Apuesta sin empate - Cuarto 2',
        wplay: '2do Cuarto',
        // betsson: '',
        // '1xbet': '',
        codere: 'Ganador 2º Cuarto (Sin Empate)',
        yaJuegos: '',
        luckia: 'Cuarto 2 - Ganador sin empate',
        sportium: '2º Cuarto - Ganador (sin empate)',
        // zamba: '',
        wonderbet: '2° Cuarto - Empate Apuesta No Válida',
        // megapuesta: '',
        fullreto: 'Segundo cuarto - apuesta sin empate',
        betboro: '2do Cuarto Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 2.º cuarto',
        dafabet: 'Ganador - 2º Cuarto',
        cashwin: 'Second quarter - draw no bet'
    },
    'Total de puntos - Cuarto 2': {
        betplay: 'Total de puntos - Cuarto 2',
        // wplay: '',
        // betsson: '',
        '1xbet': 'Total. 2 Cuarto',
        codere: 'Más/Menos Total de Puntos 2º Cuarto',
        // yaJuegos: '',
        luckia: 'Cuarto 2 - Total',
        sportium: 'Más/Menos Total de Puntos 2º Cuarto',
        zamba: '2.º cuarto - total',
        wonderbet: '2° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 2',
        fullreto: 'Cuarto segundo - total',
        betboro: '2do Cuarto Total de puntos',
        pinnacle: 'Total – 2.º cuarto',
        dafabet: 'Más/Menos - 2º Cuarto',
        cashwin: 'Second quarter - total'
    },
    '1.ª parte': {
        betplay: '1.ª parte',
        wplay: '1ª Mitad Línea de Dinero 3 Opciones',
        betsson: 'ganador - 1ra mitad',
        '1xbet': '1X2. 1 Mitad',
        // codere: '',
        // yaJuegos: '',
        luckia: '1ª mitad - 1X2',
        sportium: '1X2 1ª Mitad',
        zamba: '1º Mitad - 1x2',
        wonderbet: '1° Tiempo - Ganador (1-X-2)',
        megapuesta: '1ª Mitad',
        fullreto: '1ª Mitad - 1x2',
        betboro: '1ra Mitad: Resultado (3 vías)',
        cashwin: '1st half - 1x2',
    },
    'Apuesta sin empate - 1.ª parte': {
        betplay: 'Apuesta sin empate - 1.ª parte',
        wplay: '1er Mitad',
        betsson: 'ganador - 1ra mitad',
        // '1xbet': '',
        // codere: '',
        // yaJuegos: '',
        luckia: '1ª mitad - Ganador sin empate',
        sportium: '1ª Mitad - Ganador (sin empate)',
        zamba: '1º Mitad - Apuesta sin empate',
        wonderbet: '2° Tiempo - Empate Apuesta No Válida',
        // megapuesta: '',
        fullreto: '1ª Mitad - Apuesta sin empate',
        betboro: '1ra Mitad: Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 1.ª parte',
        dafabet: 'Ganador-1º Tiempo',
        cashwin: '1st half - draw no bet'
    },
    'Total de puntos - 1.ª parte': {
        betplay: 'Total de puntos - 1.ª parte',
        // wplay: '',
        betsson: 'total puntos - 1ra mitad',
        '1xbet': 'Total. 1 Mitad',
        codere: 'Más/Menos Total de Puntos 1ª Mitad',
        yaJuegos: '',
        luckia: '1ª mitad - Menos/Más',
        sportium: 'Más/Menos Total de Puntos 1ª Mitad',
        zamba: '1º Mitad - total',
        // wonderbet: '',
        megapuesta: 'Total Puntos en el Mitad 1',
        fullreto: '1ª Mitad - total',
        betboro: '1ra Mitad Total de Puntos',
        pinnacle: 'Total – 1st Half',
        dafabet: 'Más/Menos-1º Tiempo',
        cashwin: '1st half - total'
    },
    'Cuarto 3': {
        betplay: 'Cuarto 3',
        wplay: '3er Cuarto Línea de Dinero 3 Opciones',
        betsson: 'resultado - 3er cuarto',
        '1xbet': '1X2. 3 Cuarto',
        // codere: '',
        yaJuegos: '',
        luckia: 'Cuarto 3 - 1X2',
        sportium: '3º Cuarto - Resultado',
        zamba: '3.º cuarto - 1x2',
        wonderbet: '3° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 3',
        fullreto: 'Tercer cuarto - 1x2',
        betboro: '3er Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 3º Cuarto',
        cashwin: 'Third quarter - 1x2'
    },
    'Apuesta sin empate - Cuarto 3': {
        betplay: 'Apuesta sin empate - Cuarto 3',
        wplay: '3er Cuarto',
        betsson: 'ganador - 3er cuarto',
        // '1xbet': '',
        codere: 'Ganador 3º Cuarto (Sin Empate)',
        yaJuegos: '',
        luckia: 'Cuarto 3 - Ganador sin empate',
        sportium: '3º Cuarto - Ganador (sin empate)',
        // zamba: '',
        wonderbet: '3° Cuarto - Empate Apuesta No Válida',
        // megapuesta: '',
        fullreto: 'Tercer cuarto - apuesta sin empate',
        betboro: '3er Cuarto Ganador (2 vías)',
        dafabet: 'Ganador - 3º Cuarto',
        cashwin: 'Third quarter - draw no bet'
    },
    'Total de puntos - Cuarto 3': {
        betplay: 'Total de puntos - Cuarto 3',
        // wplay: '',
        betsson: 'total puntos - 3er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 3º Cuarto',
        yaJuegos: '',
        luckia: 'Cuarto 3 - Total',
        sportium: 'Más/Menos Total de Puntos 3º Cuarto',
        zamba: '3.º cuarto - total',
        wonderbet: '3° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 3',
        fullreto: 'Cuarto tercer - total',
        betboro: '3er Cuarto Total de puntos',
        dafabet: 'Más/Menos - 3º Cuarto',
        cashwin: 'Third quarter - total'
    },
    'Cuarto 4': {
        betplay: 'Cuarto 4',
        wplay: '4to Cuarto Money Line 3-Opciones',
        betsson: 'resultado - 4to cuarto',
        '1xbet': '1X2. 4 Cuarto',
        // codere: '',
        yaJuegos: '',
        luckia: 'Cuarto 4 - 1X2',
        sportium: '4º Cuarto - Resultado',
        zamba: '4.º cuarto - 1x2',
        wonderbet: '4° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 4',
        fullreto: 'Cuarto cuarto - 1x2',
        betboro: '4to Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 4º Cuarto',
        cashwin: 'Fourth quarter - 1x2'
    },
    'Apuesta sin empate - Cuarto 4': {
        betplay: 'Apuesta sin empate - Cuarto 4',
        wplay: '4to Cuarto',
        betsson: 'ganador - 4to cuarto',
        // '1xbet': '',
        codere: 'Ganador 4º Cuarto (Sin Empate)',
        yaJuegos: '',
        luckia: 'Cuarto 4 - Ganador sin empate',
        sportium: '4º Cuarto - Ganador (sin empate)',
        // zamba: '',
        wonderbet: '4° Cuarto - Empate Apuesta No Válida',
        // megapuesta: '',
        fullreto: 'Cuarto cuarto - apuesta sin empate',
        betboro: '4to Cuarto Ganador (2 vías)',
        dafabet: 'Ganador - 4º Cuarto',
        cashwin: 'Fourth quarter - draw no bet'
    },
    'Total de puntos - Cuarto 4': {
        betplay: 'Total de puntos - Cuarto 4',
        // wplay: '',
        betsson: 'total puntos - 4er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 4º Cuarto',
        yaJuegos: '',
        luckia: 'Cuarto 4 - Total',
        sportium: 'Más/Menos Total de Puntos 4º Cuarto',
        zamba: '4.º cuarto - total',
        wonderbet: '4° Cuarto - Total Puntos - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 4',
        fullreto: 'Cuarto cuarto - total',
        betboro: '4to Cuarto Total de puntos',
        dafabet: 'Más/Menos - 4º Cuarto',
        cashwin: 'Fourth quarter - total'
    },
    'Apuesta sin empate - 2.ª parte': {
        betplay: '2.ª parte',
        wplay: '2da Mitad',
        betsson: 'ganador - 2da mitad',
        // '1xbet': '1X2. 2 Mitad',
        // codere: '',
        // yaJuegos: '',
        luckia: '2ª mitad - Ganador sin empate',
        sportium: '2ª Mitad - Ganador (sin empate)',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - Ganador (1-X-2)',
        megapuesta: '2ª Mitad',
        fullreto: '2ª Mitad - 1x2',
        betboro: '2do Mitad: Ganador (2 vías)',
        cashwin: '2nd half - draw no bet'
    },
    'Total de puntos - 2.ª parte': {
        betplay: 'Total de puntos - 2.ª parte',
        // wplay: '',
        betsson: 'total puntos - 2do mitad',
        '1xbet': 'Total. 2 Mitad',
        codere: 'Más/Menos Total de Puntos 2ª Mitad',
        yaJuegos: '',
        luckia: '2ª mitad - Total',
        sportium: 'Más/Menos Total de Puntos 2ª Mitad',
        zamba: '2º Mitad - total',
        // wonderbet: '',
        megapuesta: 'Total Puntos en el Mitad 2',
        fullreto: '2ª Mitad - total',
        betboro: '2do Mitad Total de Puntos',
        cashwin: '2nd half - total'
    },
    '2.ª parte': {
        betplay: '2.ª parte',
        wplay: 'Segunda Mitad Línea de Dinero 3-Opciones (Tiempo Regular)',
        betsson: 'resultado - 2da mitad',
        '1xbet': '',
        // codere: '',
        yaJuegos: '',
        luckia: '2ª mitad - 1X2 (incl. prórroga)',
        sportium: 'Resultado 2ª Mitad',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - 1X2',
        megapuesta: '2ª Mitad',
        fullreto: '',
        // sbetboro: '',

    },
    '': {
        betplay: '',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
};

const betDescriptionsTennis = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Total de juegos': {
        betplay: 'Total de juegos',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Total de sets': {
        betplay: 'Total de sets',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Set 1': {
        betplay: 'Set 1',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Set 2': {
        betplay: 'Set 2',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Total de juegos - Set 1': {
        betplay: 'Total de juegos - Set 1',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    'Total de juegos - Set 2': {
        betplay: 'Total de juegos - Set 2',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
    '': {
        betplay: '',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        yaJuegos: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
    },
}

const groupByType = {
    total: 1,
    total2: 7,
    total1: 11,
    esquinas: 15,
    tarjetas: 17,
    handicap: 5,
};

const groupByTypeBasketball = {
    total1: 4,
    total2: 6,
    totalCuarto1: 9,
    totalCuarto2: 12,
    totalCuarto3: 15,
    totalCuarto4: 18,
}

module.exports = {
    categories,
    betTypesFootball,
    idsFootball,
    betTypesBaketball,
    idsBasketball,
    betTypesTennis,
    idsTennis,
    betDescriptionsFootball,
    betDescriptionsBasketball,
    groupByType,
    betDescriptionsTennis,
    groupByTypeBasketball,
}