
const categories = [
    'snooker',
    'ufc_mma',
    'table_tennis',
    'american_football',
    'cricket',
    'volleyball',
    'ice_hockey',
    'football',
    'basketball',
    'tennis',
    'baseball',
    /*/ 
    /*/
];

const betTypesFootball = [
    'Tiempo reglamentario',
    'Total de goles',
    'Doble Oportunidad',
    'Se clasifica para la siguiente ronda',
    'Ambos Equipos Marcarán',
    'Hándicap 3-Way',
    'Gol en ambas mitades',
    'Total de goles - 2.ª parte',
    'Ambos Equipos Marcarán - 2.ª parte',
    'Doble Oportunidad - 2.ª parte',
    '2.ª parte',
    '1.ª parte',
    'Total de goles - 1.ª parte',
    'Ambos Equipos Marcarán - 1.ª parte',
    'Doble Oportunidad - 1.ª parte',
    'Total de Tiros de Esquina - 1.ª parte',
    'Total de Tiros de Esquina',
    'Más Tiros de Esquina',
    'Total de tarjetas',
    'Tarjeta Roja mostrada',
    'Más Tarjetas',
];

const betTypesBaketball = [
    'Prórroga incluida',
    'Total de puntos - Prórroga incluida',
    '1.ª parte',
    'Apuesta sin empate - 1.ª parte',
    'Total de puntos - 1.ª parte',
    '2.ª parte',
    'Apuesta sin empate - 2.ª parte',
    'Total de puntos - 2.ª parte',
    'Cuarto 1',
    'Apuesta sin empate - Cuarto 1',
    'Total de puntos - Cuarto 1',
    'Cuarto 2',
    'Apuesta sin empate - Cuarto 2',
    'Total de puntos - Cuarto 2',
    'Cuarto 3',
    'Apuesta sin empate - Cuarto 3',
    'Total de puntos - Cuarto 3',
    'Cuarto 4',
    'Apuesta sin empate - Cuarto 4',
    'Total de puntos - Cuarto 4',
];

const betTypesTennis = [
    'Cuotas del partido',
    'Total de juegos',
    'Total de sets',
    'Total de minutos',
    'Set 1',
    'Set 2',
    'Total de juegos - Set 1',
    'Total de juegos - Set 2',
    'Número total de Aces',
    'Número total de juegos con quiebre',
    'Total de Doble Faltas',
];

const betTypesVolleyball = [
    'Cuotas del partido',
    'Total de puntos',
    'Total de sets',
    'Set 1',
    'Total de puntos - Set 1',
    'Set 2',
    'Total de puntos - Set 2',
    'Resultado al final del Set 2',
    'Puntos totales - Resultado al final del Set 2',
    'Set 3',
    'Total de puntos - Set 3',
];

const betTypesBaseball = [
    'Cuotas del partido',
    'Total de carreras',
    'Primer equipo que marcará',
    'Primeros con 2 Carreras (Empate: Ningún equipo llegará a 2)',
    'Primeros con 3 Carreras (Empate: Ningún equipo llegará a 3)',
    'Primeros con 4 Carreras (Empate: Ningún equipo llegará a 4)',
    'Primeros con 5 Carreras (Empate: Ningún equipo llegará a 5)',
    'Entrada 1',
    'Total de carreras - Entrada 1',
    'Ganara después de 3 entradas',
    'Ganara después de 5 entradas',
    'Más Golpe',
];

const betTypesMMA = [
    'Cuotas del partido',
    'Total de asaltos',
    'Todos los asaltos completados',
];

const betTypesIceHockey = [
    'Cuotas del partido - Tiempo reglamentario',
    'Total de goles - Tiempo reglamentario',
    'Ambos Equipos Marcarán - Tiempo reglamentario',
    'Apuesta sin empate - Tiempo reglamentario',
    'Cualquier equipo ganará sin conceder goles - Tiempo reglamentario',
    'Primero en alcanzar 1 goles (Empate: Ningún equipo llegará a 1) - Tiempo reglamentario',
    'Primero en alcanzar 2 goles (Empate: Ningún equipo llegará a 2) - Tiempo reglamentario',
    'Primero en alcanzar 3 goles (Empate: Ningún equipo llegará a 3) - Tiempo reglamentario',
    'Primero en alcanzar 4 goles (Empate: Ningún equipo llegará a 4) - Tiempo reglamentario',
    'Primero en alcanzar 5 goles (Empate: Ningún equipo llegará a 5) - Tiempo reglamentario',
    'Periodo 1',
    'Apuesta sin empate - Periodo 1',
    'Total de goles - Periodo 1',
    'Ambos equipos marcarán - Periodo 1',
    'Periodo 2',
    'Apuesta sin empate - Periodo 2',
    'Total de goles - Periodo 2',
    'Ambos equipos marcarán - Periodo 2',
    'Periodo 3',
    'Apuesta sin empate - Periodo 3',
    'Total de goles - Periodo 3',
    'Ambos equipos marcarán - Periodo 3',
];

const betTypesAmericanFootball = [
    'Prórroga incluida',
    'Total de puntos - Prórroga incluida'
];

const betTypesCricket = [
    'Cuotas del partido',
    'Ganador del sorteo',
    'Total de Eliminaciones en carrera',
    'Total de 6s',
    'Total de 4s',
    'Mayor número de puntuaciones 6',
    'Más 4s',
    'Más eliminaciones en carrera - Equipo de bateo',
    'Super Over durante el partido',
    'Half Century marcado',
    'Centena marcado',
    'Total más alto Primeros Over',
    'Total de carreras - 1ª Ball',
    'Boundary - Over 1',
    'Wicket - Over 1',
];

const betTypesSnooker = [
    'Cuotas del partido',
    'Total de Partidas',
    'Total Century breaks',
    'Break más elevado',
    'Set 1',
    'Total de puntos - Partida 1',
    'Tacada +50 en el set 1',
    'Tacada +100 en el set 1',
];

const betTypesTableTennis = [
    'Cuotas del partido',
    'Total de juegos'
];


const idsFootball = {};
for (let i = 0; i < betTypesFootball.length; i++) {
    idsFootball[betTypesFootball[i]] = i + 1;
}

const idsBasketball = {};
for (let i = 0; i < betTypesBaketball.length; i++) {
    idsBasketball[betTypesBaketball[i]] = i + 1;
}

const idsTennis = {};
for (let i = 0; i < betTypesTennis.length; i++) {
    idsTennis[betTypesTennis[i]] = i + 1;
}

const idsVolleyball = {};
for (let i = 0; i < betTypesVolleyball.length; i++) {
    idsVolleyball[betTypesVolleyball[i]] = i + 1;
}

const idsBaseball = {};
for (let i = 0; i < betTypesBaseball.length; i++) {
    idsBaseball[betTypesBaseball[i]] = i + 1;
}

const idsMMA = {};
for (let i = 0; i < betTypesMMA.length; i++) {
    idsMMA[betTypesMMA[i]] = i + 1;
}

const idsIceHokey = {};
for (let i = 0; i < betTypesIceHockey.length; i++) {
    idsIceHokey[betTypesIceHockey[i]] = i + 1;
}

const idsAmericanFootball = {};
for (let i = 0; i < betTypesAmericanFootball.length; i++) {
    idsAmericanFootball[betTypesAmericanFootball[i]] = i + 1;
}

const idsCricket = {};
for (let i = 0; i < betTypesCricket.length; i++) {
    idsCricket[betTypesCricket[i]] = i + 1;
}

const idsSnooker = {};
for (let i = 0; i < betTypesSnooker.length; i++) {
    idsSnooker[betTypesSnooker[i]] = i + 1;
}

const idsTableTennis = {};
for (let i = 0; i < betTypesTableTennis.length; i++) {
    idsTableTennis[betTypesTableTennis[i]] = i + 1;
}

const betDescriptionsFootball = {
    'Total de goles': {
        betplay: 'Total de goles',
        wplay: 'Total Goles Más/Menos de',
        betsson: 'número de goles',
        '1xbet': 'Total',
        codere: 'Más/Menos Total Goles',
        yaJuegos: 'Totales',
        luckia: 'Menos/Más',
        sportium: 'Total de goles Más/Menos',
        zamba: 'Total',
        wonderbet: 'Total Goles - Más / Menos',
        megapuesta: 'Total Goles',
        fullreto: 'Total de goles',
        betboro: 'Total de goles',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos - Tiempo Regular',
        cashwin: 'Total',
        bwin: 'Total de goles',
        lsbet: 'Gesamtzahl Tore mehr als / weniger als',
        ggbet: 'Total',
        marathon: 'Total de goles',
        leon: 'Más de / Menos de',
        stake: 'Total',
        unobet: 'Goles Más/Menos de',
        cloudbet: 'Total',
        suprabet: 'Total de goles',
        ivibet: 'Total',
        mostbet: 'Total'
    },
    'Tiempo reglamentario': {
        betplay: 'Tiempo reglamentario',
        wplay: 'Resultado Tiempo Completo',
        betsson: 'ganador del partido',
        '1xbet': '1x2',
        codere: '1X2',
        yaJuegos: '1X2',
        luckia: '1x2',
        sportium: '1X2',
        zamba: '1x2',
        wonderbet: 'Ganador',
        megapuesta: 'Final',
        fullreto: '1x2',
        betboro: 'Resultado del Partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Resultado - Tiempo Regular',
        cashwin: '1x2',
        bwin: 'Resultado del partido',
        lsbet: 'Match Ergebnis',
        ggbet: '1x2',
        marathon: 'Resultado del partido',
        leon: 'Tiempo reglamentario',
        stake: '1X2',
        unobet: 'Resultado del encuentro',
        cloudbet: 'Resultado a tiempo completo',
        suprabet: 'Resultado del Partido',
        ivibet: '1x2',
        mostbet: '1x2. Resultado final',
    },
    'Doble Oportunidad': {
        betplay: 'Doble Oportunidad',
        wplay: 'Doble Oportunidad',
        betsson: 'doble oportunidad',
        '1xbet': 'Doble oportunidad',
        codere: 'Doble Oportunidad',
        yaJuegos: 'Doble oportunidad',
        luckia: 'Doble oportunidad',
        sportium: 'Doble Oportunidad',
        zamba: 'Doble oportunidad',
        wonderbet: 'Doble Oportunidad',
        megapuesta: 'Doble Oportunidad',
        fullreto: 'Doble oportunidad',
        betboro: 'Doble Oportunidad',
        pinnacle: 'Double Chance',
        dafabet: 'Doble oportunidad - Tiempo Regular',
        cashwin: 'Double chance',
        bwin: 'Doble oportunidad',
        lsbet: 'Doppelte Chance',
        ggbet: 'Doble oportunidad',
        leon: 'Doble oportunidad',
        stake: 'Doble Oportunidad',
        unobet: 'Doble oportunidad',
        suprabet: 'Doble Oportunidad',
        ivibet: 'Doble oportunidad',
        mostbet: 'Doble oportunidad'
    },
    'Se clasifica para la siguiente ronda': {
        betplay: 'Se clasifica para la siguiente ronda',
        wplay: 'Se clasificará',
        betsson: 'avanza a la siguiente fase',
        '1xbet': 'Se clasificará',
        codere: 'Clasificarse',
        luckia: 'Se clasificará',
        sportium: 'Clasificarse',
        fullreto: 'Se clasifica',
        betboro: 'Clasificará',
        pinnacle: 'Línea de dinero – Para calificar',
        cashwin: 'Draw no bet',
        bwin: 'Se clasifica',
        lsbet: 'Zu Qualifizieren',
        marathon: 'Se clasifica para la final',
        // leon: ''
        stake: 'Equipo en avanzar',
        unobet: 'Se clasifica',
    },
    'Ambos Equipos Marcarán': {
        betplay: 'Ambos Equipos Marcarán',
        wplay: 'Ambos Equipos Anotan',
        betsson: 'ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán',
        codere: 'Marcan Ambos Equipos',
        yaJuegos: 'Ambos equipos marcarán',
        luckia: 'Ambos equipos marcarán',
        sportium: 'Marcan ambos equipos',
        zamba: 'Ambos equipos marcan',
        wonderbet: 'ambos equipos anotaran',
        megapuesta: 'Ambos Equipos Marcarán',
        fullreto: 'Ambos equipos marcan',
        betboro: 'Ambos equipos marcan',
        pinnacle: '¿Anotarán los dos equipos?',
        dafabet: 'Ambos equipos marcan - Tiempo Regular',
        bwin: 'Ambos equipos marcan',
        lsbet: 'Beide Teams treffen',
        ggbet: 'Ambos equipos marcan',
        leon: 'Ambos equipos marcan',
        stake: 'Ambos equipos para anotar',
        unobet: 'Los dos equipos marcan',
        cloudbet: 'Ambos equipos marcan',
        suprabet: 'Ambos equipos marcan',
        ivibet: 'Ambos equipos marcan',
        mostbet: 'Ambos equipos anotarán'
    },
    'Gol en ambas mitades': {
        betplay: 'Gol en ambas mitades',
        wplay: 'Se anotarán goles en ambas mitades',
        betsson: 'gol en ambos tiempos',
        '1xbet': 'Goles en ambas mitades',
        codere: 'Goles en ambas mitades',
        yaJuegos: 'Goles en ambas mitades',
        luckia: 'Goles en ambas mitades',
        // sportium: 'Ambos marcan ambas partes',
        zamba: 'Goles en ambas mitades',
        wonderbet: 'Goles en ambas mitades',
        megapuesta: 'Goles en ambas mitades',
        fullreto: 'Goles en ambas mitades',
        betboro: 'Goles en ambas mitades',
        cashwin: '1st/2nd half both teams to score',
        bwin: 'Goles que se marcan en ambas partes',
        leon: 'Inicio para anotar en ambas mitades',
        suprabet: 'Goles en ambas mitades',
        mostbet: 'Gol en los dos tiempos'
    },
    'Total de goles - 2.ª parte': {
        betplay: 'Total de goles - 2.ª parte',
        wplay: '2ª Mitad - más/Menos de',
        '1xbet': 'Total. 2 Mitad',
        codere: '2ª Parte - Más/Menos Total Goles',
        luckia: '2ª mitad - Menos/Más',
        sportium: '2ª Mitad - Total de Goles',
        zamba: '2º Mitad - total',
        wonderbet: '2° Tiempo - Más de/Menos de',
        megapuesta: '2ª M Total Goles',
        fullreto: '2ª Mitad - total',
        betboro: '2da mitad Total de  goles',
        dafabet: 'Más/Menos - Segundo tiempo',
        cashwin: '2nd half - total',
        bwin: 'Total de goles-2º tiempo',
        ggbet: '2nd half - 1x2',
        marathon: 'Total de goles - 2.º tiempo',
        leon: '2do tiempo: Más/Menos',
        stake: 'Total 2da mitad',
        cloudbet: '2ª mitad - total de goles',
        suprabet: '2da mitad Total de goles',
        ivibet: '2º Mitad - total',
        mostbet: 'Total. Segundo Tiempo'
    },
    'Ambos Equipos Marcarán - 2.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 2.ª parte',
        wplay: 'Ambos Equipos anotarán en la 2da Mitad',
        '1xbet': 'Ambos equipos anotarán. 2 Mitad',
        codere: '2ª Parte - Marcan Ambos Equipos',
        luckia: '2ª mitad - Ambos equipos marcarán',
        sportium: '2ª Mitad - Ambos equipos marcarán',
        zamba: '2º Mitad - ambos equipos marcan',
        wonderbet: '2° Tiempo - Ambos equipos marcan',
        megapuesta: '2ª Mitad Ambos Equipos Marcarán',
        fullreto: '2ª Mitad - ambos equipos marcan',
        betboro: '2da mitad Ambos equipos anotarán',
        cashwin: '2nd half - both teams to score',
        bwin: 'Ambos equipos marcan-2º tiempo',
        ggbet: '2º Mitad - ambos equipos marcan',
        stake: 'Ambos equipos a anotar en 2da mitad',
        unobet: 'Los dos equipos marcan en la segunda mitad',
        suprabet: '2da mitad Ambos equipos anotarán',
        ivibet: '2º Mitad - ambos equipos marcan',
        mostbet: 'Los dos equipos anotan. Segundo Tiempo'
    },
    'Doble Oportunidad - 2.ª parte': {
        betplay: 'Doble Oportunidad - 2.ª parte',
        '1xbet': 'Doble oportunidad. 2 Mitad',
        codere: '2ª Parte - Doble Oportunidad',
        luckia: '2ª mitad - Doble oportunidad',
        zamba: '2º Mitad - doble oportunidad',
        wonderbet: '2° Tiempo - Doble Oportunidad',
        fullreto: '2ª Mitad - doble oportunidad',
        betboro: '2da Mitad Doble Oportunidad',
        cashwin: '2nd half - total',
        bwin: 'Doble oportunidad-2º tiempo',
        ggbet: '2nd half  - Double chance',
        leon: '2do tiempo: Doble Oportunidads',
        unobet: 'Doble oportunidad, segunda mitad',
        suprabet: '2da Mitad Doble Oportunidad',
        ivibet: '2º Mitad - hándicap',
        mostbet: 'Oportunidad doble  (1X – 12 – X2). Segundo Tiempo',
    },
    '2.ª parte': {
        betplay: '2.ª parte',
        wplay: 'Resultado 2da Mitad',
        betsson: 'resultado del 2do tiempo',
        '1xbet': '1x2. 2 Mitad',
        codere: '2ª Parte - 1X2',
        luckia: '2ª mitad - 1X2',
        sportium: 'Resultado 2ª Mitad',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - Ganador (1-X-2)',
        megapuesta: '2ª Mitad',
        fullreto: '2ª Mitad - 1x2',
        betboro: 'Resultado de la Segunda Mitad',
        dafabet: 'Resultado - Segundo tiempo',
        cashwin: '2nd half - 1x2',
        bwin: 'Resultado del partido-2º tiempo',
        lsbet: 'Second Half Result',
        ggbet: '2nd half - 1x2',
        marathon: 'Resultado - 2.º tiempo',
        leon: '2do tiempo: Resultado',
        stake: 'Resultado 2da mitad',
        unobet: 'Resultado de la segunda mitad',
        cloudbet: '2ª mitad - 1x2',
        suprabet: 'Resultado de la Segunda Mitad',
        ivibet: '2º Mitad - 1x2',
        mostbet: '1x2. Resultado del 2 º tiempo',
    },
    '1.ª parte': {
        betplay: '1.ª parte',
        wplay: 'Resultado 1ra Mitad',
        betsson: 'resultado del 1ro tiempo',
        '1xbet': '1x2. 1 Mitad',
        codere: '1ª Parte - 1X2',
        luckia: '1ª mitad - 1X2',
        sportium: 'Resultado 1ª Mitad',
        zamba: '1º Mitad - 1x2',
        wonderbet: '1° Tiempo - Ganador (1-X-2)',
        megapuesta: '1ª Mitad',
        fullreto: '1ª Mitad - 1x2',
        betboro: 'Resultado de la Primera Mitad',
        dafabet: 'Resultado - Primer tiempo',
        cashwin: '1st half - 1x2',
        bwin: 'Resultado del partido-1º tiempo',
        lsbet: 'First Half Result',
        ggbet: '1st half - 1x2',
        marathon: 'Resultado - 1.º tiempo',
        leon: '1ra mitad: Resultado',
        stake: 'Resultado 1er mitad',
        unobet: 'Resultado en el descanso',
        cloudbet: 'Resultado al descanso',
        suprabet: 'Resultado de la 1ra mitad',
        ivibet: '1º Mitad - 1x2',
        mostbet: '1x2. Resultado del 1.er tiempo'
    },
    'Total de goles - 1.ª parte': {
        betplay: 'Total de goles - 1.ª parte',
        wplay: '1ra Mitad Total de Goles más/Menos de',
        '1xbet': 'Total. 1 Mitad',
        codere: '1ª Parte - Más/Menos Total Goles',
        luckia: '1ª mitad - Menos/Más',
        sportium: '1ª Mitad - Total de Goles',
        zamba: '1º Mitad - total',
        wonderbet: '1° Tiempo - Más de/Menos de',
        megapuesta: '1ª M Total Goles',
        fullreto: '1ª Mitad - total',
        betboro: 'Total de Goles de la 1ra mitad',
        pinnacle: 'Total – 1.ª parte',
        dafabet: 'Más/Menos - Primer tiempo',
        cashwin: '1st half - total',
        bwin: 'Total de goles-1º tiempo',
        lsbet: 'Half-time Totals Over/Under',
        ggbet: '1st Mitad - total',
        marathon: 'Total de goles - 1.er tiempo',
        leon: '1.er tiempo: Totales Más/Menos',
        stake: 'Total 1er mitad',
        unobet: 'Goles Más/Menos de, primera mitad',
        cloudbet: '1ª mitad - total de goles',
        suprabet: 'Total de Goles de la 1ra mitad',
        ivibet: '1º Mitad - total',
        mostbet: 'Total - Primer Tiempo'
    },
    'Ambos Equipos Marcarán - 1.ª parte': {
        betplay: 'Ambos Equipos Marcarán - 1.ª parte',
        wplay: 'Ambos Equipos anotarán en la 1er Mitad',
        betsson: '1er tiempo - ambos equipos anotan',
        '1xbet': 'Ambos equipos anotarán. 1 Mitad',
        codere: '1ª Parte - Marcan Ambos Equipos',
        luckia: '1ª mitad - Ambos equipos marcarán',
        sportium: '1ª Mitad - Ambos equipos marcarán',
        zamba: '1º Mitad - ambos equipos marcan',
        wonderbet: '1° Tiempo - Ambos equipos marcan',
        megapuesta: '1ª Mitad Ambos Equipos Marcarán',
        fullreto: '1ª Mitad - ambos equipos marcan',
        betboro: '1ra mitad: Ambos Equipos Anotarán',
        pinnacle: 'Both Teams To Score? 1st Half',
        dafabet: 'Ambos equipos marcan - Primer tiempo',
        cashwin: '1st half - 1x2 & both teams to score',
        bwin: 'Ambos equipos marcan-1º tiempo',
        lsbet: 'Half-time Both Teams To Score Yes/No',
        leon: '1.er tiempo: Ambos equipos marcan Sí/No',
        stake: 'Ambos equipos a anotar en 1er mitad',
        unobet: 'Los dos equipos marcan en la primera mitad',
        cloudbet: '1ª mitad- ambos equipos marcan',
        suprabet: '1ra mitad: Ambos Equipos Anotarán',
        ivibet: '1º Mitad - ambos equipos marcan',
        mostbet: 'Primer tiempo - Los dos equipos anotan'
    },
    'Doble Oportunidad - 1.ª parte': {
        betplay: 'Doble Oportunidad - 1.ª parte',
        wplay: 'Doble Oportunidad 1ª Mitad',
        betsson: '1er tiempo - doble oportunidad',
        '1xbet': 'Doble oportunidad. 1 Mitad',
        codere: '1ª Parte - Doble Oportunidad',
        luckia: '1ª mitad - Doble oportunidad',
        sportium: '1ª Mitad - Doble Oportunidad',
        zamba: '1º Mitad - doble oportunidad',
        wonderbet: '1° Tiempo - Doble Oportunidad',
        fullreto: '1ª Mitad - doble oportunidad',
        betboro: '1ra mitad: Doble Oportunidad',
        pinnacle: 'Double Chance 1st Half',
        dafabet: 'Doble oportunidad - Primer tiempo',
        cashwin: '1st half - double chance',
        bwin: 'Doble oportunidad-1º tiempo',
        lsbet: 'Erste Hälfte   Doppelte Chance',
        ggbet: '1st half  - Double chance',
        leon: '1.er tiempo: Doble Oportunidad',
        unobet: 'Doble oportunidad, primera mitad',
        cloudbet: '1ª mitad - Doble oportunidad',
        suprabet: '1ra mitad: Doble Oportunidad',
        ivibet: '1º Mitad - doble oportunidad',
        mostbet: 'Oportunidad Doble (1X – 12 – X2) - Primer Tiempo'
    },
    'Total de Tiros de Esquina': {
        betplay: 'Total de Tiros de Esquina',
        wplay: 'Tiros de esquina más/Menos de (9.5)',
        betsson: 'total tiros de esquina',
        '1xbet': 'Total. Saques de esquina',
        codere: 'Total de Córner Más/Menos',
        luckia: 'Menos/Más corners',
        sportium: 'Total de córners',
        zamba: 'Total córneres',
        wonderbet: 'Total tiros de esquina',
        megapuesta: 'Total Esquinas',
        fullreto: 'Total Tiros De Esquina',
        betboro: 'Córneres: Total',
        pinnacle: 'Total (Córneres) – Partido',
        dafabet: 'Corners Más/Menos - Tiempo Regular',
        cashwin: 'Total corners',
        bwin: 'Número de córners',
        lsbet: 'Total Corners Over/Under',
        ggbet: 'Córneres - Total',
        marathon: 'Total de córneres',
        unobet: 'Total de córneres',
        stake: 'Total de esquinas',
        cloudbet: 'Total de córneres',
        suprabet: 'Córneres: Total',
        ivibet: 'Total córneres',
        mostbet: 'Total. Saques de esquina'
    },
    'Más Tiros de Esquina': {
        betplay: 'Más Tiros de Esquina',
        wplay: 'Equipo con más Tiros de Esquina',
        betsson: 'mayor número de tiros de esquina',
        '1xbet': '1x2. Saques de esquina',
        codere: 'Equipo con Más Córner',
        luckia: 'Corners - 1X2',
        sportium: 'Mayor número de córners',
        zamba: 'Córner 1x2',
        wonderbet: 'Equipo que sacará más corners (1-X-2)',
        megapuesta: 'Esquninas 1X2',
        fullreto: 'Córner 1x2',
        betboro: 'Córneres: Resultado',
        dafabet: 'Más corners - Tiempo Regular',
        cashwin: 'Corner 1x2',
        bwin: 'Córners',
        lsbet: 'Team With Most Corners (With Draw)',
        ggbet: 'Córneres - 1x2',
        marathon: 'Más córneres',
        leon: 'Resultado de las esquinas',
        stake: 'Resultado en esquinas',
        unobet: 'Apuesta de córneres del partido',
        cloudbet: 'Córner 1x2',
        suprabet: 'Córneres: Resultado',
        ivibet: 'Córner 1x2',
        mostbet: '1x2 . Saques de esquina'
    },
    'Total de tarjetas': {
        betplay: 'Total de tarjetas',
        wplay: 'Total de Tarjetas (3.5)',
        betsson: 'total de tarjetas',
        '1xbet': 'Total. Tarjetas amarillas',
        codere: 'Total de Tarjetas Más/Menos',
        luckia: 'Menos/Más tarjetas (jugadores en juego)',
        sportium: 'Total de tarjetas',
        zamba: 'Total tarjetas',
        wonderbet: 'Total de tarjetas en el partido',
        megapuesta: 'Total Tarjetas',
        fullreto: 'Total tarjetas',
        betboro: 'Tarjetas Amarillas: Total',
        pinnacle: 'Total (Tarjetas) – Partido',
        dafabet: 'Bookings Más/Menos - Tiempo Regular',
        cashwin: 'Total bookings',
        bwin: 'Número total de tarjetas amarillas',
        lsbet: 'Gesamtzahl der Karten Über / Unter',
        ggbet: 'Tarjetas amarillas - Total',
        leon: 'Tarjetas Amarillas: Más/Menos',
        unobet: 'Total de tarjetas',
        cloudbet: 'Total de tarjetas',
        suprabet: 'Tarjetas Amarillas: Total',
        mostbet: 'Tarjetas Amarillas - Total'
    },
    'Tarjeta Roja mostrada': {
        betplay: 'Tarjeta Roja mostrada',
        betsson: 'tarjetas rojas',
        codere: '¿Habrá Tarjeta Roja?',
        luckia: '¿Habrá alguna expulsión en el partido? (jugadores en juego)',
        zamba: 'Expulsión',
        megapuesta: 'Expulsión',
        fullreto: 'Expulsión',
        betboro: 'Una tarjeta roja en el partido',
        dafabet: 'Expulsión (tarjeta roja) - Tiempo Regular',
        bwin: 'Tarjeta roja - Sí/No',
        ggbet: 'Expulsión',
        leon: 'Tarjeta Roja: ¿Sí/No?',
        stake: 'Tarjetas rojas',
        cloudbet: 'Expulsión',
        suprabet: 'Una tarjeta roja en el partido',
    },
    'Más Tarjetas': {
        betplay: 'Más Tarjetas',
        betsson: 'más puntos de amonestación',
        '1xbet': '1x2. Tarjetas amarillas',
        codere: 'Equipo con Más Tarjetas',
        luckia: 'Tarjetas - 1X2 (jugadores en juego)',
        zamba: 'Tarjeta 1x2',
        wonderbet: 'Equipo que verá más tarjetas en el partido (1-X-2)',
        megapuesta: '1X2 Tarjetas',
        fullreto: 'Tarjetas 1x2',
        betboro: 'Tarjetas Amarillas: Resultado',
        dafabet: 'Más Tarjetas - Tiempo Regular',
        cashwin: 'Booking 1x2',
        bwin: 'Más tarjetas amarillas',
        ggbet: 'Tarjetas amarillas - 1x2',
        marathon: 'Más tarjetas amarillas',
        leon: '1X2 Tarjetas Amarillas',
        stake: 'Linea de tarjetas amarillas',
        unobet: 'Equipo con más tarjetas',
        cloudbet: 'Tarjeta 1x2',
        mostbet: 'Tarjetas Amarillas - 1x2'
    },
    'Total de Tiros de Esquina - 1.ª parte': {
        betplay: 'Total de Tiros de Esquina - 1.ª parte',
        dafabet: 'Corners Más/Menos - Primer tiempo',
        bwin: 'Número de córners-1º tiempo',
        ggbet: '1 tiempo - Tarjetas amarillas - Total',
        marathon: 'Total de córneres - 1.er tiempo',
        leon: '1er tiempo: Córners Más/Menos',
        unobet: 'Más/Menos de Córneres primera mitad',
        suprabet: 'Córneres: Resultado de la 1ra mitad'
    },
    'Hándicap asiático - 1.ª parte': {
        betplay: 'Hándicap asiático - 1.ª parte',
        wplay: '',
        betsson: '',
        '1xbet': '',
        codere: '',
        luckia: '',
        sportium: '',
        zamba: '',
        wonderbet: '',
        megapuesta: '',
        fullreto: '',
        betboro: '',
        leon: '',
    },
    'Total asiático - 1.ª parte': {
        betplay: 'Total asiático - 1.ª parte',
        wplay: 'Handicap Asiático Total Goles 1ra Mitad',
    },
    'Hándicap 3-Way': {
        betplay: 'Hándicap 3-Way',
        wplay: 'Handicap Resultado Partido',
        betsson: 'hándicap (3 opciones)',
        '1xbet': 'Hándicap',
        codere: '1X2 Handicap',
        luckia: '1X2 - Hándicap',
        sportium: '1X2 Handicap',
        // zamba: '',
        // wonderbet: 'Handicap Europeo',
        // megapuesta: '',
        fullreto: 'Hándicap 1x2',
        betboro: ' Hándicap 3 opciones',
    },

};

const betDescriptionsBasketball = {
    'Prórroga incluida': {
        betplay: 'Prórroga incluida',
        wplay: 'Lineas del Juego',
        betsson: 'ganador - partido',
        '1xbet': 'Victoria del equipo',
        codere: 'Ganador del Partido',
        yaJuegos: 'Totales',
        luckia: 'Ganador del partido (incl. prórroga)',
        sportium: 'Handicap de Juegos',
        zamba: 'Ganador (incl. prórroga)',
        wonderbet: 'Ganador del Partido',
        megapuesta: 'Ganador (Inc. Pró.)',
        fullreto: 'Ganador (incl. prórroga)',
        betboro: 'Ganador del Partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Ganador - Partido',
        cashwin: 'Winner (incl. OT)',
        marathon: 'Ganador del partido incluyendo la prórroga',
        lsbet: 'Ganador',
        ggbet: 'Ganador (incl. prórroga)',
        leon: 'Porroga incluida',
        stake: '1X2',
        unobet: 'A ganar',
        cloudbet: 'Líneas de juego',
        suprabet: 'Ganador del Partido',
        ivibet: 'Ganador (incl. prórroga)',
        mostbet: 'Ganador (Incluido tiempo adicional)'
    },
    'Total de puntos - Prórroga incluida': {
        betplay: 'Total de puntos - Prórroga incluida',
        wplay: 'Total Puntos (Inc. Prórroga)',
        betsson: 'puntos totales',
        '1xbet': 'Total',
        codere: 'Más/Menos Puntos Totales',
        yaJuegos: 'Totales',
        luckia: 'Menos/más (incl. prórroga)',
        sportium: 'Total de puntos',
        zamba: 'Total (incl. prórroga)',
        wonderbet: 'Más / Menos',
        megapuesta: 'Total (incl. prórroga)',
        fullreto: 'Totales (incl. prórroga)',
        betboro: 'Total de puntos',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos - Partido',
        cashwin: 'Total (incl. OT)',
        marathon: 'Total de puntos',
        lsbet: 'Total Puntos Más de/Menos de',
        ggbet: 'Total (incl. prórroga)',
        leon: 'Total',
        stake: 'Total',
        unobet: 'Total',
        cloudbet: 'Total (incluye prórroga) - Líneas alternativas',
        suprabet: 'Total de puntos',
        ivibet: 'Total (incl. prórroga)',
        mostbet: 'Total (incluido tiempo adicional)'
    },
    'Cuarto 1': {
        betplay: 'Cuarto 1',
        wplay: '1er Cuarto Línea de Dinero 3 Opciones',
        betsson: 'resultado - 1er cuarto',
        '1xbet': '1X2. 1 Cuarto',
        luckia: 'Cuarto 1 - 1X2',
        sportium: '1º Cuarto -  Resultado',
        zamba: '1.º cuarto - 1x2',
        wonderbet: '1° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 1',
        fullreto: 'Primer cuarto - 1x2',
        betboro: '1ra Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 1º Cuarto',
        cashwin: 'First quarter - 1x2',
        marathon: 'Resultado del 1.er cuarto',
        ggbet: '1st cuarto - 1x2',
        leon: '1er Cuarto: Resultado',
        stake: 'Resultado 1er cuarto',
        unobet: 'Línea de dinero, 1.er cuarto, 3 opciones',
        cloudbet: 'Cuarto 1 - 1x2',
        suprabet: '1ra Cuarto Resultado (3 opciones)',
        ivibet: '1º cuarto - 1x2',
        mostbet: '1 Cuarto - 1x2',
    },
    'Apuesta sin empate - Cuarto 1': {
        betplay: 'Apuesta sin empate - Cuarto 1',
        wplay: '1er Cuarto',
        betsson: 'ganador - 1er cuarto',
        codere: 'Ganador 1º Cuarto (Sin Empate)',
        luckia: 'Cuarto 1 - Ganador sin empate',
        sportium: '1º Cuarto - Ganador (sin empate)',
        wonderbet: '1° Cuarto - Empate Apuesta No Válida',
        fullreto: 'Primer cuarto - apuesta sin empate',
        betboro: '1ra Cuarto Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 1.er cuarto',
        dafabet: 'Ganador - 1º Cuarto',
        cashwin: 'First quarter - draw no bet',
        lsbet: 'Ganador 1er Cuarto',
        ggbet: '1st quarter - Draw no bet',
        leon: '1er Cuarto: Medio tiempo',
        unobet: 'Línea de dinero, 1.er cuarto',
        suprabet: '1ra Cuarto Ganador (2 opciones)',
        ivibet: '1º cuarto - apuesta sin empate',
    },
    'Total de puntos - Cuarto 1': {
        betplay: 'Total de puntos - Cuarto 1',
        // wplay: '',
        betsson: 'total puntos - 1er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 1º Cuarto',
        luckia: 'Cuarto 1 - Total',
        sportium: 'Más/Menos Total de Puntos 1º Cuarto',
        zamba: '1.º cuarto - total',
        wonderbet: '1° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 1',
        fullreto: 'Cuarto primer - total',
        betboro: '1ra Cuarto Total de puntos',
        pinnacle: 'Total – 1.er cuarto',
        dafabet: 'Más/Menos - 1º Cuarto',
        cashwin: 'First quarter - total',
        bwin: 'Total 1er cuarto',
        marathon: 'Total de puntos - 1.er cuarto',
        lsbet: '1º Cuarto Puntos Totales Más/Menos de',
        ggbet: '1st quarter - Total',
        leon: '1er Cuarto: Total',
        stake: 'Total 1er cuarto',
        unobet: 'Total del 1.er cuarto',
        cloudbet: 'Cuarto 1 - total',
        suprabet: '1ra Cuarto Total de puntos',
        ivibet: '1º cuarto - total',
        mostbet: '1 cuarto - Total',
    },
    'Cuarto 2': {
        betplay: 'Cuarto 2',
        wplay: '2do Cuarto Money Line 3 Opciones',
        betsson: 'resultado - 2do cuarto',
        '1xbet': '1X2. 2 Cuarto',
        luckia: 'Cuarto 2 - 1X2',
        sportium: '2º Cuarto - Resultado',
        zamba: '2.º cuarto - 1x2',
        wonderbet: '2° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 2',
        fullreto: 'Segundo cuarto - 1x2',
        betboro: '2do Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 2º Cuarto',
        cashwin: 'Second quarter - 1x2',
        marathon: 'Resultado del 2.º cuarto',
        ggbet: '2nd cuarto - 1x2',
        leon: '2do Trimestre: Resultado',
        unobet: 'Línea de dinero, 2.º cuarto, 3 opciones',
        cloudbet: 'Cuarto 2 - 1x2',
        ivibet: '2º cuarto - 1x2',
        mostbet: '2 Cuarto - 1x2',
    },
    'Apuesta sin empate - Cuarto 2': {
        betplay: 'Apuesta sin empate - Cuarto 2',
        wplay: '2do Cuarto',
        codere: 'Ganador 2º Cuarto (Sin Empate)',
        luckia: 'Cuarto 2 - Ganador sin empate',
        sportium: '2º Cuarto - Ganador (sin empate)',
        wonderbet: '2° Cuarto - Empate Apuesta No Válida',
        fullreto: 'Segundo cuarto - apuesta sin empate',
        betboro: '2do Cuarto Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 2.º cuarto',
        dafabet: 'Ganador - 2º Cuarto',
        cashwin: 'Second quarter - draw no bet',
        ggbet: '2nd quarter - Draw no bet',
        unobet: 'Línea de dinero, 2.º cuarto',
        ivibet: '2º cuarto - apuesta sin empate',
    },
    'Total de puntos - Cuarto 2': {
        betplay: 'Total de puntos - Cuarto 2',
        '1xbet': 'Total. 2 Cuarto',
        codere: 'Más/Menos Total de Puntos 2º Cuarto',
        luckia: 'Cuarto 2 - Total',
        sportium: 'Más/Menos Total de Puntos 2º Cuarto',
        zamba: '2.º cuarto - total',
        wonderbet: '2° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 2',
        fullreto: 'Cuarto segundo - total',
        betboro: '2do Cuarto Total de puntos',
        pinnacle: 'Total – 2.º cuarto',
        dafabet: 'Más/Menos - 2º Cuarto',
        cashwin: 'Second quarter - total',
        marathon: 'Total de puntos - 2.º cuarto',
        ggbet: '2nd quarter - Total',
        leon: '2do Cuarto: Más/Menos',
        unobet: 'Total del 2.º cuarto',
        cloudbet: 'Cuarto 2 - total',
        ivibet: '2º cuarto - total',
        mostbet: '2 cuarto - Total',
    },
    '1.ª parte': {
        betplay: '1.ª parte',
        wplay: '1ª Mitad Línea de Dinero 3 Opciones',
        betsson: 'ganador - 1ra mitad',
        '1xbet': '1X2. 1 Mitad',
        luckia: '1ª mitad - 1X2',
        sportium: '1X2 1ª Mitad',
        zamba: '1º Mitad - 1x2',
        wonderbet: '1° Tiempo - Ganador (1-X-2)',
        megapuesta: '1ª Mitad',
        fullreto: '1ª Mitad - 1x2',
        betboro: '1ra Mitad: Resultado (3 vías)',
        cashwin: '1st half - 1x2',
        marathon: 'Resultado de la 1.ª mitad',
        ggbet: '1º Mitad - 1x2',
        leon: '1er Tiempo: Resultado',
        stake: 'Resultado 1er mitad',
        unobet: 'Línea de dinero, 1.ª mitad, 3 opciones',
        cloudbet: '1ª mitad - 1x2',
        suprabet: '1ra Mitad: Resultado (3 opciones)',
        ivibet: '1º Mitad - 1x2',
        mostbet: '1 ª mitad - 1x2',
    },
    'Apuesta sin empate - 1.ª parte': {
        betplay: 'Apuesta sin empate - 1.ª parte',
        wplay: '1er Mitad',
        betsson: 'ganador - 1ra mitad',
        luckia: '1ª mitad - Ganador sin empate',
        sportium: '1ª Mitad - Ganador (sin empate)',
        zamba: '1º Mitad - Apuesta sin empate',
        wonderbet: '2° Tiempo - Empate Apuesta No Válida',
        fullreto: '1ª Mitad - Apuesta sin empate',
        betboro: '1ra Mitad: Ganador (2 vías)',
        pinnacle: 'Línea de dinero – 1.ª parte',
        dafabet: 'Ganador-1º Tiempo',
        cashwin: '1st half - draw no bet',
        lsbet: '1ª mitad',
        leon: '1era mitad: línea de dinero',
        unobet: 'Línea de dinero, 1.ª mitad',
        cloudbet: '1ª mitad - Empate anula apuesta',
        suprabet: '1ra Mitad: Ganador (2 opciones)',
        ivibet: '1º Mitad - Apuesta sin empate'
    },
    'Total de puntos - 1.ª parte': {
        betplay: 'Total de puntos - 1.ª parte',
        betsson: 'total puntos - 1ra mitad',
        '1xbet': 'Total. 1 Mitad',
        codere: 'Más/Menos Total de Puntos 1ª Mitad',
        luckia: '1ª mitad - Menos/Más',
        sportium: 'Más/Menos Total de Puntos 1ª Mitad',
        zamba: '1º Mitad - total',
        megapuesta: 'Total Puntos en el Mitad 1',
        fullreto: '1ª Mitad - total',
        betboro: '1ra Mitad Total de Puntos',
        pinnacle: 'Total – 1st Half',
        dafabet: 'Más/Menos-1º Tiempo',
        cashwin: '1st half - total',
        marathon: 'Total de puntos - 1.ª mitad',
        lsbet: '1er Mitad Total De Puntos Más/Menos',
        ggbet: '1st half - total',
        leon: '1era mitad: Total',
        stake: 'Total 1er mitad',
        unobet: 'Total de la 1.ª mitad',
        cloudbet: '1ª mitad - total',
        suprabet: '1ra Mitad Total de Puntos',
        ivibet: '1º Mitad - total',
        mostbet: '1 ª mitad - total',
    },
    'Cuarto 3': {
        betplay: 'Cuarto 3',
        wplay: '3er Cuarto Línea de Dinero 3 Opciones',
        betsson: 'resultado - 3er cuarto',
        '1xbet': '1X2. 3 Cuarto',
        luckia: 'Cuarto 3 - 1X2',
        sportium: '3º Cuarto - Resultado',
        zamba: '3.º cuarto - 1x2',
        wonderbet: '3° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 3',
        fullreto: 'Tercer cuarto - 1x2',
        betboro: '3er Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 3º Cuarto',
        cashwin: 'Third quarter - 1x2',
        marathon: 'Resultado del 3.er cuarto',
        ggbet: '3rd cuarto - 1x2',
        leon: '3er Trimestre: Resultado',
        unobet: 'Línea de dinero, 3.er cuarto, 3 opciones',
        cloudbet: 'Cuarto 3 - 1x2',
        ivibet: '3º cuarto - 1x2',
        mostbet: '3 Cuarto - 1x2',
    },
    'Apuesta sin empate - Cuarto 3': {
        betplay: 'Apuesta sin empate - Cuarto 3',
        wplay: '3er Cuarto',
        betsson: 'ganador - 3er cuarto',
        codere: 'Ganador 3º Cuarto (Sin Empate)',
        luckia: 'Cuarto 3 - Ganador sin empate',
        sportium: '3º Cuarto - Ganador (sin empate)',
        wonderbet: '3° Cuarto - Empate Apuesta No Válida',
        fullreto: 'Tercer cuarto - apuesta sin empate',
        betboro: '3er Cuarto Ganador (2 vías)',
        dafabet: 'Ganador - 3º Cuarto',
        cashwin: 'Third quarter - draw no bet',
        ggbet: '3rd quarter - Draw no bet',
        unobet: 'Línea de dinero, 3.er cuarto',
        ivibet: '3º cuarto - apuesta sin empate',
    },
    'Total de puntos - Cuarto 3': {
        betplay: 'Total de puntos - Cuarto 3',
        betsson: 'total puntos - 3er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 3º Cuarto',
        luckia: 'Cuarto 3 - Total',
        sportium: 'Más/Menos Total de Puntos 3º Cuarto',
        zamba: '3.º cuarto - total',
        wonderbet: '3° Cuarto - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 3',
        fullreto: 'Cuarto tercer - total',
        betboro: '3er Cuarto Total de puntos',
        dafabet: 'Más/Menos - 3º Cuarto',
        cashwin: 'Third quarter - total',
        marathon: 'Total de puntos - 3.er cuarto',
        leon: '3er Cuarto: Más/Menos',
        unobet: 'Total del 3.er cuarto',
        cloudbet: 'Cuarto 3 - total',
        ivibet: '3º cuarto - total',
        mostbet: '3 cuarto - Total',
    },
    'Cuarto 4': {
        betplay: 'Cuarto 4',
        wplay: '4to Cuarto Money Line 3-Opciones',
        betsson: 'resultado - 4to cuarto',
        '1xbet': '1X2. 4 Cuarto',
        luckia: 'Cuarto 4 - 1X2',
        sportium: '4º Cuarto - Resultado',
        zamba: '4.º cuarto - 1x2',
        wonderbet: '4° Cuarto - Ganador (1-X-2)',
        megapuesta: 'Cuarto 4',
        fullreto: 'Cuarto cuarto - 1x2',
        betboro: '4to Cuarto Resultado (3 vías)',
        dafabet: 'Resultado - 4º Cuarto',
        cashwin: 'Fourth quarter - 1x2',
        ggbet: '4th cuarto - 1x2',
        unobet: 'Línea de dinero, 4.º cuarto, 3 opciones',
        cloudbet: 'Cuarto 4 - 1x2',
        ivibet: '4º cuarto - 1x2',
        mostbet: '4 Cuarto - 1x2',
    },
    'Apuesta sin empate - Cuarto 4': {
        betplay: 'Apuesta sin empate - Cuarto 4',
        wplay: '4to Cuarto',
        betsson: 'ganador - 4to cuarto',
        codere: 'Ganador 4º Cuarto (Sin Empate)',
        luckia: 'Cuarto 4 - Ganador sin empate',
        sportium: '4º Cuarto - Ganador (sin empate)',
        wonderbet: '4° Cuarto - Empate Apuesta No Válida',
        fullreto: 'Cuarto cuarto - apuesta sin empate',
        betboro: '4to Cuarto Ganador (2 vías)',
        dafabet: 'Ganador - 4º Cuarto',
        cashwin: 'Fourth quarter - draw no bet',
        ggbet: '4th quarter - Draw no bet',
        unobet: 'Línea de dinero, 4.º cuarto',
        ivibet: '4º cuarto - apuesta sin empate',
    },
    'Total de puntos - Cuarto 4': {
        betplay: 'Total de puntos - Cuarto 4',
        betsson: 'total puntos - 4er cuarto',
        '1xbet': 'Total. 1 Cuarto',
        codere: 'Más/Menos Total de Puntos 4º Cuarto',
        luckia: 'Cuarto 4 - Total',
        sportium: 'Más/Menos Total de Puntos 4º Cuarto',
        zamba: '4.º cuarto - total',
        wonderbet: '4° Cuarto - Total Puntos - Más / Menos',
        megapuesta: 'Total Puntos Cuarto 4',
        fullreto: 'Cuarto cuarto - total',
        betboro: '4to Cuarto Total de puntos',
        dafabet: 'Más/Menos - 4º Cuarto',
        cashwin: 'Fourth quarter - total',
        marathon: 'Total de puntos - 4.º cuarto',
        leon: '4to Cuarto: Más/Menos (Tiempo regular)',
        unobet: 'Total del 4.º cuarto',
        cloudbet: 'Cuarto 4 - total',
        ivibet: '4º cuarto - total',
        mostbet: '4 cuarto - Total',
    },
    'Apuesta sin empate - 2.ª parte': {
        betplay: '2.ª parte',
        wplay: '2da Mitad',
        betsson: 'ganador - 2da mitad',
        luckia: '2ª mitad - Ganador sin empate',
        sportium: '2ª Mitad - Ganador (sin empate)',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - Ganador (1-X-2)',
        megapuesta: '2ª Mitad',
        fullreto: '2ª Mitad - 1x2',
        betboro: '2do Mitad: Ganador (2 vías)',
        cashwin: '2nd half - draw no bet',
        ggbet: '2º Mitad - Apuesta sin empate',
        unobet: 'Línea de dinero, 2.ª mitad',
        ivibet: '2º mitad - apuesta sin empate (incl. prórroga)'
    },
    'Total de puntos - 2.ª parte': {
        betplay: 'Total de puntos - 2.ª parte',
        // wplay: '',
        betsson: 'total puntos - 2do mitad',
        '1xbet': 'Total. 2 Mitad',
        codere: 'Más/Menos Total de Puntos 2ª Mitad',
        luckia: '2ª mitad - Total',
        sportium: 'Más/Menos Total de Puntos 2ª Mitad',
        zamba: '2º Mitad - total',
        // wonderbet: '',
        megapuesta: 'Total Puntos en el Mitad 2',
        fullreto: '2ª Mitad - total',
        betboro: '2do Mitad Total de Puntos',
        cashwin: '2nd half - total',
        marathon: 'Total de puntos - 2.ª mitad',
        ggbet: '2º Mitad - total',
        unobet: 'Total de la 2.ª mitad',
        cloudbet: '2ª mitad - total (no incluye prórroga)',
        ivibet: '2º mitad - total (incl. prórroga)',
        mostbet: '2 ª mitad - total',
    },
    '2.ª parte': {
        betplay: '2.ª parte',
        wplay: 'Segunda Mitad Línea de Dinero 3-Opciones (Tiempo Regular)',
        betsson: 'resultado - 2da mitad',
        '1xbet': '',
        luckia: '2ª mitad - 1X2 (incl. prórroga)',
        sportium: 'Resultado 2ª Mitad',
        zamba: '2º Mitad - 1x2',
        wonderbet: '2° Tiempo - 1X2',
        megapuesta: '2ª Mitad',
        marathon: 'Resultado de la 2.ª mitad',
        ggbet: '2º Mitad - 1x2',
        leon: '2° Tiempo: Resultado (Tiempo reglamentario)',
        unobet: 'Línea de dinero, 2.ª mitad, 3 opciones',
        cloudbet: '2ª mitad - 1x2',
        ivibet: '2º Mitad - 1x2',
        mostbet: '2 ª mitad - 1x2',
    },
};

const betDescriptionsTennis = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        wplay: 'Ganador del partido',
        betsson: 'ganador del partido',
        '1xbet': '1X2',
        codere: 'Ganador del partido',
        luckia: 'Ganador del partido',
        sportium: 'Ganador del Partido',
        zamba: 'Ganador',
        wonderbet: 'Ganador del Partido',
        megapuesta: 'Ganador',
        fullreto: 'Ganador',
        betboro: 'Ganador del Partido',
        pinnacle: 'Ganador del partido',
        dafabet: 'Ganador - Partido',
        cashwin: 'Winner',
        bwin: '¿Ganador del partido (1-2)',
        lsbet: 'Ganador del partido',
        ggbet: 'Ganador',
        marathon: 'Resultado del partido',
        leon: 'Cuotas del partido',
        stake: '1X2',
        unobet: 'A ganar',
        cloudbet: 'Ganador',
        suprabet: 'Ganador del Partido',
        ivibet: 'Ganador',
        mostbet: '1x2. Resultado final'
    },
    'Total de juegos': {
        betplay: 'Total de juegos',
        wplay: 'Total de Rondas',
        betsson: 'total de juegos del partido',
        '1xbet': 'Total',
        codere: 'Total de Juegos Más/Menos',
        luckia: 'Menos/Más juegos',
        sportium: 'Total de juegos',
        zamba: 'Total juegos',
        wonderbet: 'Más / Menos',
        megapuesta: 'Total de Juegos',
        fullreto: 'Total juegos',
        betboro: 'Total de Juegos',
        pinnacle: 'Total (Juegos) – Partido',
        dafabet: 'Más/Menos Games - Partido',
        cashwin: 'Total games',
        bwin: '¿Cuántos juegos se disputarán en el partido?',
        lsbet: 'Menos de/Más de Juegos',
        ggbet: 'Total juegos',
        marathon: 'Total de juegos',
        leon: 'Juegos totales',
        stake: 'Total',
        unobet: 'Total de partidos',
        cloudbet: 'Total de juegos (el Super Tie Break cuenta como 1 juego)',
        suprabet: 'Total de Juegos',
        ivibet: 'Total juegos',
        mostbet: 'Total'
    },
    'Total de sets': {
        betplay: 'Total de sets',
        betsson: 'total de sets jugados',
        '1xbet': 'Total de sets',
        codere: 'Número Total de Sets',
        betboro: 'Total de Sets',
        pinnacle: 'Total (Sets) – Partido',
        marathon: 'Total de sets',
        leon: 'Sets Totales - Más/Menos',
        unobet: 'Sets totales',
        cloudbet: 'Total de sets',
        suprabet: 'Total de Sets'
    },
    'Set 1': {
        betplay: 'Set 1',
        wplay: 'Ganador Set (Set 1)',
        betsson: 'ganador del 1 set',
        '1xbet': '1X2. 1 Set',
        codere: 'Ganador del Set 1',
        luckia: 'Set 1 - Ganador',
        sportium: 'Ganador Set 1',
        zamba: '1.º set - ganador',
        wonderbet: '1° Set - Ganador',
        megapuesta: 'Ganador Set 1',
        fullreto: 'Primer set - ganador',
        betboro: '1er set Ganador',
        pinnacle: 'Línea de dinero (Sets) – 1.º set',
        dafabet: 'Ganador - 1er Set',
        cashwin: 'First set - winner',
        bwin: '¿Quién ganará el 1er set?',
        lsbet: 'Ganador 1º Set',
        ggbet: '1st set - ganador',
        marathon: 'Resultado del 1.er set',
        leon: 'Conjunto 1 - Ganador',
        stake: 'Ganador 1er sets',
        unobet: 'Ganador del primer set',
        cloudbet: '1 set - ganador',
        suprabet: '1er set Ganador',
        ivibet: '1º set - ganador',
        mostbet: '1 set - 1x2',
    },
    'Set 2': {
        betplay: 'Set 2',
        wplay: 'Ganador Set (Set 2)',
        betsson: 'ganador del 2 set',
        '1xbet': '1X2. 2 Set',
        codere: 'Ganador del Set 2',
        luckia: 'Set 2 - Ganador',
        sportium: 'Ganador Set 2',
        zamba: '2.º set - ganador',
        megapuesta: 'Ganador Set 2',
        fullreto: 'Segundo set - ganador',
        betboro: '2er set Ganador',
        pinnacle: 'Línea de dinero (Sets) – 2.º set',
        dafabet: 'Ganador - 2º Set',
        cashwin: 'Second set - winner',
        bwin: '¿Quién ganará el 2° set?',
        lsbet: 'Ganador 2º Set',
        ggbet: '2nd set - ganador',
        leon: 'Conjunto 2 - Ganador',
        unobet: 'Ganador del segundo set',
        cloudbet: '2 set - ganador',
        suprabet: '2er set Ganador',
        ivibet: '2º set - ganador',
        mostbet: '2 set - 1x2',
    },
    'Total de juegos - Set 1': {
        betplay: 'Total de juegos - Set 1',
        '1xbet': 'Total. 1 Set',
        codere: 'Set 1 - Más/Menos Juegos Totales',
        luckia: 'Set 1 - Menos/Más juegos',
        sportium: 'Más/Menos Juegos Totales en Set 1',
        zamba: '1.º set - total juegos',
        megapuesta: 'Total de Juegos Set 1',
        fullreto: 'Primer set - total juegos',
        betboro: '1er Set total de juegos',
        pinnacle: 'Total (Juegos) – 1.º set',
        dafabet: 'Más/Menos Games - 1er Set',
        cashwin: 'First set - total games',
        bwin: '¿Cuántos juegos se disputarán en el 1er set?',
        lsbet: '1º Set Menos de/Más de',
        marathon: 'Total de juegos del 1.er set',
        leon: 'Set 1 - Total de juegos Más/Menos',
        unobet: 'Juegos, total del 1.er set',
        cloudbet: 'Total de juegos en el 1 set',
        suprabet: '1er Set total de juegos',
        ivibet: '1º set - total juegos',
        mostbet: '1 set - total',
    },
    'Total de juegos - Set 2': {
        betplay: 'Total de juegos - Set 2',
        '1xbet': 'Total. 2 Set',
        codere: 'Set 2 - Más/Menos Juegos Totales',
        luckia: 'Set 2 - Menos/Más juegos',
        zamba: '2.º set - total juegos',
        betboro: '2er Set total de juegos',
        dafabet: 'Más/Menos Games - 2º Set',
        lsbet: '2º Set Menos de/Más de',
        ggbet: '2nd set - total games',
        unobet: 'Juegos, total del 2.º set',
        cloudbet: 'Total de juegos en el 2 set',
        ivibet: '2º set - total juegos',
        mostbet: '2 set - total',
    },
    'Total de Doble Faltas': {
        betplay: 'Total de Doble Faltas',
        betsson: 'total de doble faltas',
        codere: 'Total de dobles faltas',
        betboro: 'Total de Faltas Dobles',
        bwin: '¿Cuántas dobles faltas se producirán en el partido?',
        marathon: 'Total de dobles faltas',
        unobet: 'Dobles faltas superior / inferior',
        mostbet: 'Double faults - Total'
    },
    'Número total de juegos con quiebre': {
        betplay: 'Número total de juegos con quiebre',
        betsson: 'total quiebres del servicio',
        codere: 'Total de roturas (excluido Tie-Break)',
        betboro: 'Total de quiebres',
        bwin: '¿Cuántos breaks en el partido?',
        unobet: 'Encuentro - Total de tie breaks',
    },
    'Número total de Aces': {
        betplay: 'Número total de Aces',
        betsson: 'total de aces',
        codere: 'Total de aces',
        betboro: 'Total de Aces',
        bwin: '¿Cuántos puntos de saque directos (aces) se anotarán en el partido?',
        marathon: 'Total de aces',
        unobet: 'Aces superior / inferior',
        mostbet: 'Aces - Total'
    },
}

const betDescriptionsVolleyball = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        wplay: 'Uno contra Uno',
        betsson: 'ganador',
        '1xbet': '1X2',
        codere: 'Ganador del Partido',
        luckia: 'Ganador del partido',
        sportium: 'Ganador del Partido',
        zamba: 'Ganador',
        wonderbet: 'Ganador',
        megapuesta: 'Ganador',
        fullreto: 'Ganador',
        betboro: 'Ganador del Partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Ganador - Partido',
        cashwin: 'Winner',
        bwin: '¿Ganador del partido? (1-2)',
        lsbet: 'Ganador del partido',
        ggbet: 'Ganador',
        marathon: 'Gana el partido',
        stake: '1X2',
        unobet: 'Ganar el partido',
        cloudbet: 'Ganador',
        suprabet: 'Ganador del Partido',
        ivibet: 'Ganador',
        mostbet: '1x2. Resultado final'
    },
    'Total de puntos': {
        betplay: 'Total de puntos',
        wplay: 'Más de/Menos de Total de Puntos',
        betsson: 'puntos totales del partido',
        '1xbet': 'Total',
        codere: 'Más/Menos Puntos Totales',
        luckia: 'Menos/Más puntos',
        sportium: 'Más/Menos Puntos Totales',
        zamba: 'Total puntos',
        wonderbet: 'Total Puntos (Más de/Menos de)',
        fullreto: 'Total puntos',
        betboro: 'Total de puntos',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos (Puntos) - Partido',
        cashwin: 'Total points',
        bwin: 'Total de puntos',
        lsbet: 'Total de Puntos Más de / Menos de',
        ggbet: 'Total points',
        marathon: 'Total de puntos',
        stake: 'Puntos en total',
        unobet: 'Puntos Más/Menos de',
        cloudbet: 'Total de puntos',
        suprabet: 'Total de puntos',
        ivibet: 'Total puntos',
        mostbet: 'Total'
    },
    'Total de sets': {
        betplay: 'Total de sets',
        wplay: 'Total de Sets más/Menos de',
        '1xbet': 'Total de sets',
        codere: 'Total de Sets en el Partido',
        fullreto: 'Total de sets',
        betboro: 'Total de Sets',
        ggbet: 'Total sets',
        stake: 'Total de Sets',
        unobet: 'Total de sets del partido',
        cloudbet: 'Total de sets',
        suprabet: 'Total de Sets',
        mostbet: 'Numero de sets'
    },
    'Set 1': {
        betplay: 'Set 1',
        wplay: 'Ganador Set (Set 1)',
        betsson: 'Set 1 Ganador',
        '1xbet': '1X2. 1 Set',
        codere: 'Ganador Set 1',
        luckia: 'Set 1 - Ganador',
        sportium: 'Ganador Set 1',
        zamba: '1.º set - ganador',
        wonderbet: '1° Set - Ganador',
        fullreto: 'Primer set - ganador',
        betboro: '1er set Ganador',
        pinnacle: 'Línea de dinero (Puntos) – 1.º set',
        cashwin: 'First set - winner',
        bwin: '¿Qué equipo ganará el primer set?',
        lsbet: 'Ganador 1r Set',
        ggbet: '1st set - ganador',
        marathon: 'Gana el 1.er set',
        stake: 'Ganador 1er set',
        unobet: '1.er set - A ganar',
        suprabet: '1er set Ganador',
        ivibet: '1º set - ganador',
        mostbet: '1 ° set - Ganador',
    },
    'Total de puntos - Set 1': {
        betplay: 'Total de puntos - Set 1',
        wplay: 'Total Puntos por Set (Set 1) (45.5)s',
        betsson: '1er Set Total de Puntos',
        '1xbet': 'Total. 2 Set',
        codere: 'Set 1 - Puntos Totales',
        luckia: 'Set 1 - Menos/Más puntos',
        sportium: 'Set 1 - Total de puntos',
        zamba: '1.º set - total puntos',
        wonderbet: '1° Set - Totales',
        fullreto: 'Primer set - total puntos',
        betboro: '1ra Set Total de puntos',
        pinnacle: 'Total (Puntos) – 1.º set',
        dafabet: 'Más/Menos (Puntos) - 1er Set',
        bwin: '¿Cuántos puntos se anotarán en el 1er set?',
        lsbet: '1r Set Puntos Totales Más de / Menos de',
        ggbet: '1st set - total points',
        marathon: 'Total de puntos del 1.er set',
        stake: 'Total 1er set',
        unobet: 'Puntos Más/Menos de, 1.er set',
        suprabet: '1ra Set Total de puntos',
        ivibet: '1º set - total puntos',
        mostbet: '1 set - total ',
    },
    'Set 2': {
        betplay: 'Set 2',
        wplay: 'Ganador Set (Set 2)',
        '1xbet': '1X2. 2 Set',
        codere: 'Ganador Set 2',
        luckia: 'Set 2 - Ganador',
        sportium: 'Ganador Set 2',
        zamba: '2.º set - ganador',
        wonderbet: '2° Set - Ganador',
        fullreto: 'Segundo set - ganador',
        // betboro: '',
        pinnacle: 'Línea de dinero (Puntos) – 2.º set',
        lsbet: 'Ganador 2do Set',
        ggbet: '2nd set - ganador',
        marathon: 'Gana el 2.º set',
        stake: 'Ganador 2do set',
        unobet: '2.º set - A ganar',
        ivibet: '2º set - ganador',
        mostbet: '2 ° set - Ganador',
    },
    'Total de puntos - Set 2': {
        betplay: 'Total de puntos - Set 2',
        '1xbet': 'Total. 2 Set',
        codere: 'Set 2 - Puntos Totales',
        luckia: 'Set 2 - Menos/Más puntos',
        sportium: 'Set 2 - Total de puntos',
        zamba: '2.º set - total puntos',
        wonderbet: '2° Set - Totales',
        fullreto: 'Segundo set - total puntos',
        pinnacle: 'Total (Puntos) – 2.º set',
        lsbet: '2do Set Puntos Totales Más de / Menos de',
        ggbet: '2nd set - total points',
        marathon: 'Total de puntos del 2.º set',
        ivibet: '2º set - total puntos',
        mostbet: '2 set - total ',
    },
    'Set 3': {
        betplay: 'Set 3',
        wplay: 'Ganador Set (Set 3)',
        '1xbet': '1X2. 3 Set',
        codere: 'Ganador Set 3',
        luckia: 'Set 3 - Ganador',
        sportium: 'Ganador Set 3',
        zamba: '3.º set - ganador',
        wonderbet: '3° Set - Ganador',
        fullreto: 'Tercer set - ganador',
        pinnacle: 'Línea de dinero (Puntos) – 3.º set',
        bwin: '¿Qué equipo ganará el 3° set?',
        lsbet: 'Ganador 3er Set',
        ggbet: '3rd set - ganador',
        marathon: 'Gana el 3.er set',
        stake: 'Ganardor 3er set',
        unobet: '3.er set - A ganar',
        ivibet: '3º set - ganador',
        mostbet: '3 ° set - Ganador',
    },
    'Total de puntos - Set 3': {
        betplay: 'Total de puntos - Set 3',
        '1xbet': 'Total. 3 Set',
        codere: 'Set 3 - Puntos Totales',
        luckia: 'Set 3 - Menos/Más puntos',
        sportium: 'Set 3 - Total de puntos',
        zamba: '3.º set - total puntos',
        wonderbet: '3° Set - Totales',
        fullreto: 'Tercer set - total puntos',
        pinnacle: 'Total (Puntos) – 3.º set',
        lsbet: '3er Set Puntos Totales Más de / Menos de',
        ggbet: '3rd set - total points',
        marathon: 'Total de puntos del 3.er set',
        ivibet: '3º set - total puntos',
        mostbet: '3 set - total ',
    },
}

const betDescriptionsBaseball = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        betsson: 'moneyline',
        '1xbet': '1x2',
        codere: 'Ganador del Partido',
        luckia: 'Ganador (incl. extra innings)',
        sportium: 'Handicap de Juegos',
        zamba: 'Ganador (incl. extra innings)',
        wonderbet: 'Ganador',
        megapuesta: 'Ganador (Inc. Pró.)',
        fullreto: 'Ganador (incl. extra innings)',
        betboro: 'Ganador',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: '',
        cashwin: 'Winner (incl. extra innings)',
        lsbet: 'Ganador',
        ggbet: 'Ganador (incl. extra innings)',
        marathon: 'Resultado del partido',
        stake: '1X2',
        unobet: 'A ganar',
        cloudbet: 'Líneas de juego',
        suprabet: 'Ganador',
        ivibet: 'Ganador (incl. extra innings)',
        mostbet: 'Winner '
    },
    'Total de carreras': {
        betplay: 'Total de carreras',
        betsson: 'carreras en total',
        '1xbet': 'Total',
        codere: 'Total de Carreras Más/Menos',
        luckia: 'Menos/Más carreras (incl. extra innings)',
        sportium: 'Total de carreras',
        zamba: 'Total (incl. extra innings)',
        wonderbet: 'Más/Menos (Con tiempo Extra)',
        megapuesta: 'Total Puntos',
        fullreto: 'Total (incl. extra innings)',
        betboro: 'Carreras totaless',
        pinnacle: 'Total – Partido',
        cashwin: 'Total (incl. extra innings)',
        bwin: 'Total',
        lsbet: 'Puntos totales Sobre/Debajo',
        ggbet: 'Total (incl. extra innings)',
        marathon: 'Total de carreras',
        stake: 'Total',
        unobet: 'Total de carreras',
        cloudbet: 'Total (incluye prórroga) - Líneas alternativas',
        suprabet: 'Carreras totales',
        ivibet: 'Total (incl. extra innings)',
        mostbet: 'Total (incluye entradas extra)'
    },
    'Total de carreras - Entrada 1': {
        betplay: 'Total de carreras - Entrada 1',
        betsson: 'carreras totales de la primera entrada',
        '1xbet': 'Total. 1 Entrada',
        codere: '1ª Entrada Más/Menos Carreras',
        wonderbet: '1° Inning - Más / Menos',
        megapuesta: '',
        fullreto: 'Primer inning - total',
        betboro: '1ra Inning total de carreras',
        pinnacle: 'Total – 1.ª entrada',
        cashwin: 'First inning - total',
        ggbet: 'Inning 1st - Total',
        marathon: 'Total de carreras en la 1.ª entrada',
        unobet: '1.er inning - Total de carreras',
        cloudbet: '1 inning - Total',
        suprabet: '1ra Inning total de carreras'
    },
    'Primer equipo que marcará': {
        betplay: 'Primer equipo que marcará',
        '1xbet': 'Primera carrera',
        sportium: 'Primer Equipo en Marcar',
        wonderbet: 'Primero Equipo a Marcar',
        betboro: 'Primer equipo en anotar',
        pinnacle: 'Team To Score 1st Run',
        lsbet: 'First Team To Scores',
        suprabet: 'Primer equipo en anotar',
        mostbet: 'Primera carrera'
    },
    'Primeros con 3 Carreras (Empate: Ningún equipo llegará a 3)': {
        betplay: 'Primeros con 3 Carreras (Empate: Ningún equipo llegará a 3)',
        betboro: 'Primero en llegar a 3 carreras',
    },
    'Primeros con 4 Carreras (Empate: Ningún equipo llegará a 4)': {
        betplay: 'Primeros con 4 Carreras (Empate: Ningún equipo llegará a 4)',
        betboro: 'Primero en llegar a 4 carreras',
    },
    'Primeros con 5 Carreras (Empate: Ningún equipo llegará a 5)': {
        betplay: 'Primeros con 5 Carreras (Empate: Ningún equipo llegará a 5)',
        betboro: 'Primero en llegar a 5 carreras',
    },
    'Entrada 1': {
        betplay: 'Entrada 1',
        '1xbet': '1x2. 1 Entrada',
        codere: '1X2 Resultado de la 1ª Entrada',
        luckia: 'Inning 1 - 1x2',
        sportium: 'Entrada 1 - Resultado',
        fullreto: 'Primer inning - 1x2',
        betboro: '1ra Inning resultado',
        pinnacle: 'Línea de dinero – 1.ª entrada',
        cashwin: 'First inning - 1x2',
        ggbet: 'Inning 1st - 1x2',
        marathon: 'Resultado de la 1.ª entrada',
        unobet: '1.er inning - Línea de dinero, 3 opciones',
        cloudbet: '1 inning - 1x2',
        suprabet: '1ra Inning resultado',
        ivibet: '1º inning - 1x2',
        mostbet: '1 entrada - 1x2'
    },
    'Ganara después de 3 entradas': {
        betplay: 'Ganara después de 3 entradas',
        betboro: 'Líder después de 3 entradas',
    },
    'Más Golpe': {
        betplay: 'Más Golpe',
        '1xbet': 'Anotación de los hits',
        betboro: 'Hits Resultado',
        marathon: 'Más hits',
        unobet: 'Más hits',
    },
}

const betDescriptionsMMA = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        betsson: 'ganador de la pelea',
        codere: 'Ganador del Combate',
        luckia: 'Ganador del partido',
        sportium: 'Ganador del Partido',
        zamba: 'Ganador',
        wonderbet: 'Ganador',
        megapuesta: 'Ganador',
        fullreto: 'Ganador',
        betboro: 'Ganador',
        pinnacle: 'Línea de dinero – Lucha',
        cashwin: 'Winner',
        bwin: 'Ganador del combate',
        lsbet: 'GANADOR DE LA PELEA',
        ggbet: 'Ganador',
        stake: '1X2',
        unobet: 'Ganar un combate',
        cloudbet: 'Ganador de pelea',
        suprabet: 'Ganador',
        ivibet: 'Ganador',
        mostbet: 'Ganador'
    },
    'Total de asaltos': {
        betplay: 'Total de asaltos',
        betsson: 'número de Rounds',
        sportium: 'Total de asaltos',
        zamba: 'Total',
        wonderbet: 'Totales',
        fullreto: 'Total',
        betboro: 'Total de rounds',
        pinnacle: 'Total – Lucha',
        cashwin: 'Total',
        bwin: 'Número total de rounds - Más/menos',
        lsbet: 'NÚMERO DE ASALTOS',
        ggbet: 'Total Number of Rounds',
        stake: 'Total de rondas',
        unobet: 'Asaltos totales',
        cloudbet: 'Total',
        ivibet: 'Total'
    },
    'Todos los asaltos completados': {
        betplay: 'Todos los asaltos completados',
        wplay: 'Pelea llegará al final',
        betsson: '¿la pelea va a decisión?',
        sportium: 'Se completarán todos los asaltos',
        zamba: 'La Pelea Se Durará Hastas',
        fullreto: 'Se completarán todos los asaltos',
        betboro: 'La pelea durará hasta al final',
        cashwin: 'Will the fight go the distance',
        bwin: 'El combate se decide a los puntos',
        unobet: 'Luchar y completar todos los asaltos',
        ivibet: 'La pelea se durará hasta'
    },
}

const betDescriptionsIceHokey = {
    "Cuotas del partido - Tiempo reglamentario": {
        "betplay": "Cuotas del partido - Tiempo reglamentario",
        "wplay": "3 Opciones",
        "betsson": "ganador del partido",
        "1xbet": "1x2",
        "codere": "1X2 Resultado del Partido",
        "yaJuegos": "",
        "luckia": "1X2",
        "sportium": "1X2 Resultado del partido (Sin Prórroga)",
        "zamba": "1x2",
        "wonderbet": "Ganador (1-X-2)",
        "megapuesta": "1X2",
        "fullreto": "1x2",
        "betboro": "Resultado del partido (tiempo regular)",
        "pinnacle": "Línea de dinero – Tiempo reglamentario",
        "dafabet": "Resultado - Tiempo Regular",
        "cashwin": "1x2",
        "bwin": "1 X 2 (tiempo reglamentario)",
        "lsbet": "Apuesta de 60 min",
        "ggbet": "1x2",
        "marathon": "Resultado",
        "stake": "1X2",
        "unobet": "Resultado del partido 3 periodos (tiempo reglamentario)",
        cloudbet: '1x2 (no incluye prórroga)',
        suprabet: 'Resultado del partido (tiempo regular)',
        ivibet: '1x2',
        mostbet: '1x2. Resultado final'
    },
    "Total de goles - Tiempo reglamentario": {
        "betplay": "Total de goles - Tiempo reglamentario",
        "wplay": "Total Goles Más/Menos de",
        "betsson": "total de goles",
        "1xbet": "Total",
        "sportium": "Total de goles (Sin Prórroga)",
        "zamba": "Total",
        "wonderbet": "Total Goles - Más / Menos",
        "betboro": "Total de goles (tiempo regular)",
        "pinnacle": "Total – Tiempo reglamentario",
        "dafabet": "Total de Goles Más/Menos - Tiempo Regular",
        "cashwin": "Totales",
        "lsbet": "Total Match Goals Over/Under",
        "ggbet": "Total",
        "marathon": "Total de goles",
        "stake": "Total",
        "unobet": "Más/menos goles (tiempo reglamentario)",
        suprabet: 'Total de goles (tiempo regular)',
        ivibet: 'Total',
        mostbet: 'Total'
    },
    "Ambos Equipos Marcarán - Tiempo reglamentario": {
        "betplay": "Ambos Equipos Marcarán - Tiempo reglamentario",
        wplay: 'Ambos Equipos Anotan',
        "1xbet": "Ambos equipos anotarán",
        "codere": "Marcan Ambos Equipos",
        "luckia": "Ambos equipos marcarán",
        "fullreto": "Ambos equipos marcan",
        "betboro": "Ambos equipos marcarán (tiempo regular)",
        "dafabet": "Ambos equipos marcan - Tiempo Regular",
        "cashwin": "Both Teams To Score",
        "ggbet": "Ambos equipos marcan",
        "stake": "Ambos equipos para anotar",
        suprabet: 'Ambos equipos marcarán (tiempo regular)',
        ivibet: 'Ambos equipos marcan',
        mostbet: 'Ambos equipos anotarán'
    },
    "Apuesta sin empate - Tiempo reglamentario": {
        "betplay": "Apuesta sin empate - Tiempo reglamentario",
        "betsson": "ganador",
        "codere": "Ganador del Partido",
        "sportium": "Apuesta sin empate",
        "unobet": "Ganador sin empate (tiempo reglamentario)",
        cloudbet: 'Líneas de juego',
        ivibet: 'Apuesta sin empate',
        mostbet: 'Victorias del equipo'
    },
    "Cualquier equipo ganará sin conceder goles - Tiempo reglamentario": {
        "betplay": "Cualquier equipo ganará sin conceder goles - Tiempo reglamentario",
        "1xbet": "Victoria con portería a cero",
        "stake": "Any Team To Win Without Conceding A Goal - Regular Time",
        mostbet: 'Gana con la portería a cero'
    },
    "Primero en alcanzar 1 goles (Empate: Ningún equipo llegará a 1) - Tiempo reglamentario": {
        "betplay": "Primero en alcanzar 1 goles (Empate: Ningún equipo llegará a 1) - Tiempo reglamentario",
        "wplay": "Próximo Equipo en Anotar (Gol 1)",
        "luckia": "Primer gol",
        "sportium": "Próximo equipo en marcar - Gol #1 (Sin Prórroga)",
        "zamba": "1.º gol",
        "megapuesta": "Próximo Gol 1",
        "fullreto": "Primer gol",
        "betboro": "Primer equipo en anotar (tiempo regular)",
        "dafabet": "Equipo que marca el 1º Gol - Tiempo Regular",
        "cashwin": "First goal",
        "bwin": "¿Qué equipo marcará el primer gol en el primer periodo?",
        "marathon": "Primer equipo que marca un gol",
        "stake": "Primer gol por",
        suprabet: 'Primer equipo en anotar (tiempo regular)'
    },
    "Primero en alcanzar 2 goles (Empate: Ningún equipo llegará a 2) - Tiempo reglamentario": {
        "betplay": "Primero en alcanzar 2 goles (Empate: Ningún equipo llegará a 2) - Tiempo reglamentario",
        "betsson": "llega a 2 goles",
        "1xbet": "Primero en llegar 2",
    },
    "Primero en alcanzar 3 goles (Empate: Ningún equipo llegará a 3) - Tiempo reglamentario": {
        "betplay": "Primero en alcanzar 3 goles (Empate: Ningún equipo llegará a 3) - Tiempo reglamentario",
        "betsson": "llega a 3 goles",
        "1xbet": "Primero en llegar 3",
    },
    "Primero en alcanzar 4 goles (Empate: Ningún equipo llegará a 4) - Tiempo reglamentario": {
        "betplay": "Primero en alcanzar 4 goles (Empate: Ningún equipo llegará a 4) - Tiempo reglamentario",
        "betsson": "llega a 4 goles",
        "1xbet": "Primero en llegar 4",
    },
    "Primero en alcanzar 5 goles (Empate: Ningún equipo llegará a 5) - Tiempo reglamentario": {
        "betplay": "Primero en alcanzar 5 goles (Empate: Ningún equipo llegará a 5) - Tiempo reglamentario",
        "betsson": "llega a 5 goles",
        "1xbet": "Primero en llegar 5",
    },
    "Periodo 1": {
        "betplay": "Periodo 1",
        "wplay": "1er Período",
        "betsson": "ganador del período 1",
        "1xbet": "1x2. 1 Periodo",
        "codere": "1º Periodo - Resultado 1X2",
        "luckia": "Período 1 - 1X2",
        "sportium": "1º Periodo - Resultado",
        "zamba": "1.º periodo - 1x2",
        "wonderbet": "1° Periodo - Ganador (1-X-2)",
        "fullreto": "Primer periodo - 1x2",
        "betboro": "1ra Periodo resultado",
        "dafabet": "Resultado - 1er período",
        "lsbet": "1st Period Winner",
        "ggbet": "1st periodo - 1x2",
        "marathon": "Resultado - 1.er período",
        "stake": "Ganador 1er periodo",
        "unobet": "1.er periodo - Línea de dinero, 3 opciones",
        cloudbet: '1 período - 1x2',
        suprabet: '1ra Periodo resultado',
        ivibet: '1 periodo - 1x2',
        mostbet: '1 período - 1x2',
    },
    "Apuesta sin empate - Periodo 1": {
        "betplay": "Apuesta sin empate - Periodo 1",
        "codere": "1º Periodo - Ganador (Sin Empate)",
        "luckia": "Período 1 - Ganador sin empate",
        "zamba": "1.º periodo - apuesta sin empate",
        "fullreto": "Primer periodo - Apuesta sin empate",
        "pinnacle": "Línea de dinero – 1.er periodo",
        "dafabet": "Ganador - 1er período",
        "lsbet": "1st Period Money Line",
        "ggbet": "1st periodo - apuesta sin empate",
        "unobet": "1.er periodo - A ganar",
        cloudbet: '1 periodo - Ganador',
        ivibet: '1 periodo - apuesta sin empate',
    },
    "Total de goles - Periodo 1": {
        "betplay": "Total de goles - Periodo 1",
        "betsson": "goles del 1er período",
        "1xbet": "Total. 1 Periodo",
        "codere": "1º Periodo - Total de Goles",
        "luckia": "Período 1 - Menos/Más goles",
        "sportium": "1º Periodo - Total de goles",
        "zamba": "1.º periodo - total",
        "fullreto": "Primer periodo - total",
        "betboro": "1ra Periodo total de goles",
        "pinnacle": "Total – 1.er periodo",
        "ggbet": "1st periodo - total",
        "marathon": "Total de goles - 1.er período",
        "stake": "Total 1er periodo",
        "unobet": "1.er periodo - Más/menos goles",
        cloudbet: '1 periodo - total',
        suprabet: '1ra Periodo total de goles',
        ivibet: '1 periodo - total',
        mostbet: '1 período - total',
    },
    "Ambos equipos marcarán - Periodo 1": {
        "betplay": "Ambos equipos marcarán - Periodo 1",
        "betsson": "ambos equipos anotan - 1er período",
        "1xbet": "Ambos equipos anotarán. 1 Periodo",
        "codere": "1º Periodo - Marcan Ambos Equipos",
        "luckia": "1.º periodo - ambos equipos marcan",
        "fullreto": "Primer periodo - ambos equipos marcan",
        "betboro": "1ra Periodo Ambos Equipos Anotarán",
        "dafabet": "Ambos equipos marcan - 1er período",
        "unobet": "1.er periodo - Los dos equipos marcan",
        cloudbet: '1 periodo - ambos equipos a marcar',
        suprabet: '1ra Periodo Ambos Equipos Anotarán',
        ivibet: '1 periodo - ambos equipos marcan',
        mostbet: '1 período - ambos equipos marcarán',
    },
    "Periodo 2": {
        "betplay": "Periodo 2",
        "wplay": "2do Período",
        "1xbet": "1x2. 2 Periodo",
        "codere": "2º Periodo - Resultado 1X2",
        "luckia": "Período 2 - 1X2",
        "zamba": "2.º periodo - 1x2",
        "wonderbet": "2° Periodo - Ganador (1-X-2)",
        "fullreto": "Segundo periodo - 1x2",
        "betboro": "2do Periodo resultado",
        "dafabet": "Resultado - 2º Período ",
        "lsbet": "2nd Period Winner",
        "ggbet": "2nd periodo - 1x2",
        "marathon": "Resultado - 2.º período",
        "stake": "Ganador 2do periodo",
        "unobet": "2.º periodo - Línea de dinero, 3 opciones",
        cloudbet: '2 período - 1x2',
        suprabet: '2do Periodo resultado',
        ivibet: '2 periodo - 1x2',
        mostbet: '2 período - 1x2',
    },
    "Apuesta sin empate - Periodo 2": {
        "betplay": "Apuesta sin empate - Periodo 2",
        "codere": "2º Periodo - Ganador (Sin Empate)",
        "luckia": "Período 2 - Ganador sin empate",
        "zamba": "2.º periodo - apuesta sin empate",
        "fullreto": "Segundo periodo - Apuesta sin empate",
        "pinnacle": "Línea de dinero – 2.º periodo",
        "dafabet": "Ganador - 3rd Period",
        "lsbet": "2nd Period Money Line",
        "ggbet": "2nd periodo - apuesta sin empate",
        "unobet": "2.º periodo - A ganar",
        cloudbet: '2 periodo - Ganador',
        ivibet: '2 periodo - apuesta sin empate',
    },
    "Total de goles - Periodo 2": {
        "betplay": "Total de goles - Periodo 2",
        "1xbet": "Total. 2 Periodo",
        "codere": "2º Periodo - Total de Goles",
        "luckia": "Período 2 - Menos/Más goles",
        "zamba": "2.º periodo - total",
        "fullreto": "Segundo periodo - total",
        "betboro": "2do Periodo total de goles",
        "pinnacle": "Total – 2.º periodo",
        "lsbet": "Goles totales Segundo período Sobre/Debajo",
        "ggbet": "2nd periodo - total",
        "marathon": "Total de goles - 2.º período",
        "stake": "Total 2do periodo",
        "unobet": "2.º periodo - Más/menos goles",
        cloudbet: '2 periodo - total',
        suprabet: '2do Periodo total de goles',
        ivibet: '2 periodo - total',
        mostbet: '2 período - total',
    },
    "Ambos equipos marcarán - Periodo 2": {
        "betplay": "Ambos equipos marcarán - Periodo 2",
        "betsson": "ambos equipos anotan - 2do período",
        "1xbet": "Ambos equipos anotarán. 2 Periodo",
        "codere": "2º Periodo - Marcan Ambos Equipos",
        "sportium": "2.º periodo - ambos equipos marcan",
        "fullreto": "Segundo periodo - ambos equipos marcan",
        "betboro": "2do Periodo Ambos Equipos Anotarán",
        "dafabet": "Ambos equipos marcan - 2º Período",
        cloudbet: '2 periodo - ambos equipos a marcar',
        suprabet: '2do Periodo Ambos Equipos Anotarán',
        ivibet: '2 periodo - ambos equipos marcan',
        mostbet: '2 período - ambos equipos marcarán',
    },
    "Periodo 3": {
        "betplay": "Periodo 3",
        "wplay": "3er Período",
        "1xbet": "1x2. 3 Periodo",
        "codere": "3º Periodo - Resultado 1X2",
        "luckia": "Período 3 - 1X2",
        "zamba": "3.º periodo - 1x2",
        "wonderbet": "3° Periodo - Ganador (1-X-2)",
        "fullreto": "Tercer periodo - 1x2",
        "betboro": "3er Periodo resultado",
        "dafabet": "Resultado - 3rd Period",
        "lsbet": "3rd Period Winner",
        "ggbet": "3rd periodo - 1x2",
        "marathon": "Resultado - 3.er período",
        "stake": "Ganador 3er periodo",
        "unobet": "3.er periodo - Línea de dinero, 3 opciones",
        cloudbet: '3 período - 1x2',
        suprabet: '3er Periodo resultado',
        ivibet: '3 periodo - 1x2',
        mostbet: '3 período - 1x2',
    },
    "Apuesta sin empate - Periodo 3": {
        "betplay": "Apuesta sin empate - Periodo 3",
        "codere": "3º Periodo - Ganador (Sin Empate)",
        "luckia": "Período 3 - Ganador sin empate",
        "zamba": "3.º periodo - apuesta sin empate",
        "fullreto": "Segundo periodo - Apuesta sin empate",
        "pinnacle": "Total – 3.er periodo",
        "dafabet": "Ganador - 3rd Period",
        "lsbet": "3rd Period Money Line",
        "ggbet": "3rd periodo - apuesta sin empate",
        "unobet": "3.er periodo - A ganar",
        cloudbet: '3 periodo - Ganador',
        ivibet: '3 periodo - apuesta sin empate',
    },
    "Total de goles - Periodo 3": {
        "betplay": "Total de goles - Periodo 3",
        "1xbet": "Total. 3 Periodo",
        "codere": "3º Periodo - Total de Goles",
        "luckia": "Período 3 - Menos/Más goles",
        "zamba": "3.º periodo - total",
        "fullreto": "Tercer periodo - total",
        "betboro": "3er Periodo total de goles",
        "pinnacle": "Total – 3.er periodo",
        "lsbet": "Goles totales Tercer período Sobre/Debajo",
        "ggbet": "3rd periodo - total",
        "marathon": "Total de goles - 3.er período",
        "stake": "Total 3er periodo",
        "unobet": "3.er periodo - Más/menos goles",
        cloudbet: '3 periodo - total',
        suprabet: '3er Periodo total de goles',
        ivibet: '3 periodo - total',
        mostbet: '3 período - total',
    },
    "Ambos equipos marcarán - Periodo 3": {
        "betplay": "Ambos equipos marcarán - Periodo 3",
        "betsson": "ambos equipos anotan - 3er período",
        "1xbet": "Ambos equipos anotarán. 3 Periodo",
        "codere": "3º Periodo - Marcan Ambos Equipos",
        "sportium": "3.º periodo - ambos equipos marcan",
        "fullreto": "Tercer periodo - ambos equipos marcan",
        "betboro": "3er Periodo Ambos Equipos Anotarán",
        "dafabet": "Ambos equipos marcan - 3rd Period",
        cloudbet: '3 periodo - ambos equipos a marcar',
        suprabet: '3er Periodo Ambos Equipos Anotarán',
        ivibet: '3 periodo - ambos equipos marcan',
        mostbet: '3 período - ambos equipos marcarán',
    },
}

const betDescriptionsAmericanFootball = {
    'Prórroga incluida': {
        betplay: 'Prórroga incluida',
        wplay: 'Lineas del Juego',
        betsson: 'moneyline',
        '1xbet': '1x2',
        codere: 'Ganador del Partido',
        luckia: 'Ganador del partido (incl. prórroga)',
        sportium: 'Handicap de Juegos',
        zamba: 'Ganador (incl. prórroga)',
        wonderbet: 'Ganador del Partido',
        megapuesta: 'Ganador (Inc. Pró.)',
        fullreto: 'Ganador (incl. prórroga)',
        betboro: 'Ganador',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Ganador - Partido',
        cashwin: 'Winner (incl. OT)',
        lsbet: 'Money Line (Including Overtime)',
        marathon: 'Gana el partido',
        stake: '1X2',
        unobet: 'A ganar',
        cloudbet: 'Líneas de juego',
        suprabet: 'Ganador',
        ivibet: 'Ganador (incl. prórroga)',
        mostbet: 'Ganador (incluido TE)'
    },
    'Total de puntos - Prórroga incluida': {
        betplay: 'Total de puntos - Prórroga incluida',
        betsson: 'puntos totales',
        '1xbet': 'Total',
        codere: 'Más/Menos Total de Puntos',
        luckia: 'Total puntos (incl. prórroga)',
        zamba: 'Total (incl. prórroga)',
        wonderbet: 'Total Puntos - Más / Menos',
        megapuesta: 'Total Puntos (Inc. Pró)',
        fullreto: 'Totales (incl. prórroga)',
        betboro: 'Total de puntos',
        pinnacle: 'Total – Partido',
        dafabet: 'Más/Menos - Partido',
        cashwin: 'Total (incl. OT)',
        bwin: 'Total',
        lsbet: 'Total Points Over/Under (Including Overtime)',
        marathon: 'Total de puntos',
        stake: 'Total',
        unobet: 'Total',
        cloudbet: 'Total',
        suprabet: 'Total de puntos',
        ivibet: 'Total (incl. prórroga)',
        mostbet: 'Total (incl. TE)'
    },
}

const betDescriptionsCricket = {
    'Cuotas del partido': {
        betplay: 'Cuotas del partido',
        wplay: 'Uno contra Uno',
        betsson: 'ganador del partido – sin empate',
        '1xbet': 'Victoria del equipo',
        sportium: 'Ganador del Partido',
        zamba: 'Ganador (incl. super over)',
        wonderbet: 'Winner',
        megapuesta: 'Ganador',
        fullreto: 'Ganador (incl. super over)',
        betboro: 'Ganador del partido',
        pinnacle: 'Línea de dinero – Partido',
        dafabet: 'Ganador - Partido',
        bwin: '1 2 (incl. super over)',
        lsbet: 'Ganador del partido',
        ggbet: 'Winner (incl. super over)',
        marathon: 'Resultado del partido',
        stake: '1X2',
        unobet: 'Ganar',
        cloudbet: 'Ganador (incluye súper overs)',
        suprabet: 'Ganador del partido',
        ivibet: 'Ganador (incl. super over)',
        mostbet: 'Ganador (incluido super over)'
    },
    'Ganador del sorteo': {
        betplay: 'Ganador del sorteo',
        wplay: 'Ganador del Toss',
        '1xbet': 'Quién ganará el sorteo',
        sportium: 'Gana el sorteo inicial',
        betboro: 'Ganará el lanzamiento',
        dafabet: 'Who will win the toss? (Toss is Boss) - Partido',
        unobet: 'A ganar el sorteo',
        suprabet: 'Ganará el lanzamiento',
        ivibet: 'Qué equipo gana el sorteo'
    },
    'Mayor número de puntuaciones 6': {
        betplay: 'Mayor número de puntuaciones 6',
        wplay: 'Equipo con Mayor Numero de Sixes',
        betsson: 'most Match Sixes',
        sportium: 'Mayor número de seises',
        betboro: 'Más seises',
        dafabet: 'Most sixes - Partido',
        stake: 'Mayor anotador de sixes (seises)',
        unobet: 'Más seises',
        ivibet: 'Más seises'
    },
    'Más 4s': {
        betplay: 'Más 4s',
        betsson: 'más cuatros del partido',
        sportium: 'Mayor número de cuatros',
        dafabet: 'Most fours - Partido',
        stake: 'Mayor anotador de fours (cuatros)',
        ivibet: 'Más cuatros'
    },
    'Half Century marcado': {
        betplay: 'Half Century marcado',
        betboro: 'Un cincuenta será anotado en el Partido',
        suprabet: 'Un cincuenta será anotado en el Partido',
        ivibet: 'Cualquier jugador marca 50'
    },
    'Centena marcado': {
        betplay: 'Centena marcado',
        betboro: 'Un cien será anotado en el Partido',
        bwin: '¿Habrá un century en la partida?',
        suprabet: 'Un cien será anotado en el Partido',
        ivibet: 'Cualquier jugador marca 100'
    },
}

const betDescriptionsTableTennis = {
    'Cuotas del partido': {
        "betplay": "Cuotas del partido",
        "wplay": "Ganador del partido",
        "betsson": "ganador del partido",
        "1xbet": "1x2",
        "codere": "Ganador del Partido",
        "yaJuegos": "",
        "luckia": "Ganador del partido",
        "sportium": "Ganador del partido",
        "zamba": "Ganador",
        "wonderbet": "Ganador del Encuentro",
        "megapuesta": "Ganador",
        "fullreto": "Ganador",
        "betboro": "Ganador del Partido",
        "dafabet": "Ganador - Partido ",
        "cashwin": "Ganador",
        "bwin": "1 2 - ¿Quién ganará?",
        "ggbet": "Ganador",
        "marathon": "Gana el partido",
        "stake": "1X2",
        "unobet": "A ganar",
        "cloudbet": "Ganador",
        "suprabet": "Ganador del Partido",
        "ivibet": "Ganador",
        "mostbet": "1X2. RESULTADO FINAL"
    },
    'Total de juegos': {
        betplay: 'Total de juegos'
    }
}

const betDescriptionsSnooker = {
    "Cuotas del partido": {
        "betplay": "Cuotas del partido",
        "wplay": "Partida - Ganador (Frame 4)",
        "betsson": "Match Winner",
        "1xbet": "1x2",
        "codere": "1X2 Resultado del Partido",
        "sportium": "1X2",
        "zamba": "1x2",
        "megapuesta": "Ganador",
        "fullreto": "1x2",
        "betboro": "Resultado del Partido",
        "dafabet": "Resultado - Partido",
        "cashwin": "1x2",
        "bwin": "1 X 2",
        "ggbet": "1x2",
        "marathon": "Gana la partida",
        "stake": "1X2",
        "suprabet": "Resultado del Partido",
        "ivibet": "1x2",
        "mostbet": "1x2"
    },
    'Total de Partidas': {
        "betplay": 'Total de Partidas',
        "1xbet": "Total",
        "codere": "Más/Menos Total de Frames",
        "betboro": "Total de partidas",
        "marathon": "Total de frames",
        "stake": "Total de partidas",
        "unobet": "Total de partidas",
        "suprabet": "Total de partidas"
    },
    'Total Century breaks': {
        "betplay": 'Total Century breaks',
        "suprabet": "Total de centuries"
    },
    'Break más elevado': {
        "betplay": 'Break más elevado',
        "marathon": "Break más alto - jugador",
        "suprabet": "Quiebre más alto en la partida"
    },
    'Set 1': {
        "betplay": 'Set 1',
        "1xbet": "1x2. 1 frame",
        "codere": "Ganador del 1er Frame",
        "sportium": "Tanda 1 - Ganador",
        "fullreto": "Primer frame - ganador",
        "betboro": "1ra Partida ganador",
        "cashwin": "Primer frame - ganador",
        "bwin": "¿Quién ganará el primer frame?",
        "ggbet": "1st frame - winner",
        "marathon": "Resultado - 1.er frame",
        "suprabet": "1ra Partida ganador",
        "ivibet": "1 frame - ganador",
        "mostbet": "1 tanda - quién ganará la tanda"
    },
    'Total de puntos - Partida 1': {
        "betplay": 'Total de puntos - Partida 1',
        "1xbet": "Total. 1 frame",
        "sportium": "Tanda 1 - Total de puntos",
        "betboro": "1ra Partida total de puntos",
        "suprabet": "1ra Partida total de puntos"
    },
    'Tacada +50 en el set 1': {
        "betplay": 'Tacada +50 en el set 1',
        "wplay": "50 Break? (Frame 4)",
        "1xbet": "Break de 50 o más puntos. 1 frame",
        "sportium": "50 Break en tanda 1"
    },
    'Tacada +100 en el set 1': {
        "betplay": 'Tacada +100 en el set 1',
        "wplay": "100 Break? (Frame 4)",
        "1xbet": "Break de 100 o más puntos. 1 frame",
        "sportium": "100 Break en tanda 1"
    }
}

const groupByType = {
    total: 1,
    total2: 7,
    total1: 12,
    esquinas: 16,
    tarjetas: 18,
    handicap: 5,
};

const groupByTypeBasketball = {
    total1: 4,
    total2: 6,
    totalCuarto1: 9,
    totalCuarto2: 12,
    totalCuarto3: 15,
    totalCuarto4: 18,
}

module.exports = {
    categories,
    betTypesFootball,
    idsFootball,
    betTypesBaketball,
    idsBasketball,
    betTypesTennis,
    idsTennis,
    idsVolleyball,
    betDescriptionsVolleyball,
    betDescriptionsFootball,
    betDescriptionsBasketball,
    groupByType,
    betDescriptionsTennis,
    groupByTypeBasketball,
    betTypesVolleyball,
    betDescriptionsBaseball,
    idsBaseball,
    betTypesBaseball,
    idsMMA,
    betTypesMMA,
    betDescriptionsMMA,
    idsIceHokey,
    betTypesIceHockey,
    betDescriptionsIceHokey,
    betDescriptionsAmericanFootball,
    idsAmericanFootball,
    betTypesAmericanFootball,
    betDescriptionsCricket,
    idsCricket,
    betTypesCricket,
    idsSnooker,
    betDescriptionsSnooker,
    betTypesSnooker,
    idsTableTennis,
    betDescriptionsTableTennis,
    betTypesTableTennis,
}